import { createContext, useContext, useState, useEffect } from 'react'

const DemoVeterinaryContext = createContext(null)

// Datos de ejemplo para el demo de veterinaria
const generateVeterinaryDemoData = () => {
  const today = new Date()
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1)
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)

  // Fechas para citas y alertas
  const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1)
  const nextWeek = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7)
  const inTwoWeeks = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 14)

  // Fechas de vencimiento para medicamentos
  const nearExpiry = new Date(today.getFullYear(), today.getMonth() + 1, 15)
  const farExpiry = new Date(today.getFullYear() + 1, today.getMonth(), 1)

  return {
    user: {
      uid: 'demo-veterinary-user',
      email: 'demo@veterinaria.com',
      displayName: 'Usuario Demo Veterinaria',
      photoURL: null,
    },
    business: {
      businessName: 'VETERINARIA HUELLITAS FELICES SAC',
      name: 'VETERINARIA HUELLITAS FELICES SAC',
      ruc: '20567891234',
      address: 'Av. La Marina 2580, San Miguel',
      phone: '01-5678901',
      email: 'contacto@huellitasfelices.com',
      website: 'www.huellitasfelices.com',
      logoUrl: '/demologo.png',
      companySlogan: 'CUIDAMOS A TU MASCOTA COMO PARTE DE NUESTRA FAMILIA',
      mode: 'veterinary',
      businessMode: 'veterinary',
    },
    // Pacientes (mascotas) con información de sus dueños
    customers: [
      {
        id: '1',
        documentType: '1',
        documentNumber: '45678901',
        name: 'María García López',
        email: 'maria.garcia@email.com',
        phone: '987654321',
        address: 'Av. Brasil 1234, Jesús María',
        pets: [
          {
            id: 'pet1',
            name: 'Max',
            species: 'Perro',
            breed: 'Golden Retriever',
            birthDate: new Date(2020, 5, 15),
            weight: 32,
            color: 'Dorado',
            sex: 'Macho',
            sterilized: true,
            microchip: '985141234567890',
            allergies: ['Pollo'],
            conditions: [],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 30),
            nextVaccine: nextWeek,
            vaccineType: 'Refuerzo Séxtuple',
          }
        ]
      },
      {
        id: '2',
        documentType: '1',
        documentNumber: '32165498',
        name: 'Carlos Mendoza Ríos',
        email: 'carlos.mendoza@email.com',
        phone: '987654322',
        address: 'Jr. Camaná 456, Cercado de Lima',
        pets: [
          {
            id: 'pet2',
            name: 'Luna',
            species: 'Gato',
            breed: 'Persa',
            birthDate: new Date(2021, 2, 20),
            weight: 4.5,
            color: 'Blanco',
            sex: 'Hembra',
            sterilized: true,
            microchip: '985141234567891',
            allergies: [],
            conditions: ['Sobrepeso leve'],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 15),
            nextVaccine: inTwoWeeks,
            vaccineType: 'Triple Felina',
          },
          {
            id: 'pet3',
            name: 'Michi',
            species: 'Gato',
            breed: 'Común Europeo',
            birthDate: new Date(2022, 8, 10),
            weight: 3.8,
            color: 'Atigrado',
            sex: 'Macho',
            sterilized: false,
            microchip: null,
            allergies: [],
            conditions: [],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 60),
            nextVaccine: tomorrow,
            vaccineType: 'Triple Felina',
          }
        ]
      },
      {
        id: '3',
        documentType: '1',
        documentNumber: '71234567',
        name: 'Ana Torres Vega',
        email: 'ana.torres@email.com',
        phone: '987654323',
        address: 'Av. Salaverry 789, San Isidro',
        pets: [
          {
            id: 'pet4',
            name: 'Rocky',
            species: 'Perro',
            breed: 'Bulldog Francés',
            birthDate: new Date(2019, 11, 5),
            weight: 12,
            color: 'Atigrado',
            sex: 'Macho',
            sterilized: true,
            microchip: '985141234567892',
            allergies: ['Maíz', 'Soya'],
            conditions: ['Problemas respiratorios'],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7),
            nextVaccine: null,
            vaccineType: null,
          }
        ]
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '72345678',
        name: 'Pedro Ruiz Castro',
        email: 'pedro.ruiz@email.com',
        phone: '987654324',
        address: 'Av. Arequipa 1500, Lince',
        pets: [
          {
            id: 'pet5',
            name: 'Coco',
            species: 'Perro',
            breed: 'Poodle',
            birthDate: new Date(2018, 3, 22),
            weight: 8,
            color: 'Blanco',
            sex: 'Macho',
            sterilized: true,
            microchip: '985141234567893',
            allergies: [],
            conditions: ['Diabetes controlada'],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 14),
            nextVaccine: nextWeek,
            vaccineType: 'Rabia',
          },
          {
            id: 'pet6',
            name: 'Nieve',
            species: 'Conejo',
            breed: 'Holland Lop',
            birthDate: new Date(2023, 1, 14),
            weight: 1.8,
            color: 'Blanco',
            sex: 'Hembra',
            sterilized: false,
            microchip: null,
            allergies: [],
            conditions: [],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 45),
            nextVaccine: null,
            vaccineType: null,
          }
        ]
      },
      {
        id: '5',
        documentType: '1',
        documentNumber: '73456789',
        name: 'Rosa Mendez Luna',
        email: 'rosa.mendez@email.com',
        phone: '987654325',
        address: 'Jr. Lampa 890, Centro de Lima',
        pets: [
          {
            id: 'pet7',
            name: 'Toby',
            species: 'Perro',
            breed: 'Labrador',
            birthDate: new Date(2021, 7, 8),
            weight: 28,
            color: 'Negro',
            sex: 'Macho',
            sterilized: false,
            microchip: '985141234567894',
            allergies: [],
            conditions: [],
            lastVisit: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
            nextVaccine: inTwoWeeks,
            vaccineType: 'Séxtuple + Rabia',
          }
        ]
      },
    ],
    // Servicios veterinarios
    services: [
      { id: 'srv1', name: 'Consulta General', price: 50.00, duration: 30, category: 'consulta' },
      { id: 'srv2', name: 'Vacunación', price: 80.00, duration: 20, category: 'vacunacion' },
      { id: 'srv3', name: 'Desparasitación', price: 35.00, duration: 15, category: 'prevencion' },
      { id: 'srv4', name: 'Baño y Corte', price: 60.00, duration: 60, category: 'estetica' },
      { id: 'srv5', name: 'Corte de Uñas', price: 20.00, duration: 15, category: 'estetica' },
      { id: 'srv6', name: 'Limpieza Dental', price: 150.00, duration: 45, category: 'dental' },
      { id: 'srv7', name: 'Cirugía de Esterilización', price: 350.00, duration: 120, category: 'cirugia' },
      { id: 'srv8', name: 'Ecografía', price: 120.00, duration: 30, category: 'diagnostico' },
      { id: 'srv9', name: 'Rayos X', price: 100.00, duration: 30, category: 'diagnostico' },
      { id: 'srv10', name: 'Análisis de Sangre', price: 80.00, duration: 20, category: 'laboratorio' },
      { id: 'srv11', name: 'Hospitalización (por día)', price: 120.00, duration: 1440, category: 'hospitalizacion' },
      { id: 'srv12', name: 'Emergencia', price: 100.00, duration: 60, category: 'emergencia' },
    ],
    // Productos/medicamentos veterinarios
    products: [
      // ========== VACUNAS ==========
      {
        id: '1',
        code: 'VAC001',
        name: 'Vacuna Séxtuple Canina',
        description: 'Protege contra Moquillo, Hepatitis, Parvovirus, Parainfluenza, Leptospira y Coronavirus',
        price: 85.00,
        cost: 45.00,
        stock: 50,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b1', lotNumber: 'LOT-VAC-001', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '2',
        code: 'VAC002',
        name: 'Vacuna Triple Felina',
        description: 'Protege contra Rinotraqueitis, Calicivirus y Panleucopenia',
        price: 75.00,
        cost: 40.00,
        stock: 35,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b2', lotNumber: 'LOT-VAC-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      {
        id: '3',
        code: 'VAC003',
        name: 'Vacuna Antirrábica',
        description: 'Vacuna contra la rabia para perros y gatos',
        price: 45.00,
        cost: 20.00,
        stock: 80,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b3', lotNumber: 'LOT-VAC-003', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      // ========== ANTIPARASITARIOS ==========
      {
        id: '4',
        code: 'PAR001',
        name: 'Desparasitante Interno Canino',
        description: 'Tabletas antiparasitarias de amplio espectro - Caja x 4 tabletas',
        price: 35.00,
        cost: 15.00,
        stock: 60,
        unit: 'CAJA',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b4', lotNumber: 'LOT-PAR-001', expiryDate: farExpiry, quantity: 60, isExpired: false },
        ],
      },
      {
        id: '5',
        code: 'PAR002',
        name: 'Pipeta Antipulgas y Garrapatas',
        description: 'Protección mensual contra pulgas, garrapatas y ácaros - Para perros de 10-25kg',
        price: 55.00,
        cost: 28.00,
        stock: 45,
        unit: 'PIPETA',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b5', lotNumber: 'LOT-PAR-002', expiryDate: nearExpiry, quantity: 45, isExpired: false },
        ],
      },
      {
        id: '6',
        code: 'PAR003',
        name: 'Collar Antipulgas',
        description: 'Collar antiparasitario de larga duración (8 meses) - Talla M/L',
        price: 120.00,
        cost: 65.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b6', lotNumber: 'LOT-PAR-003', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      // ========== ANTIBIÓTICOS ==========
      {
        id: '7',
        code: 'ANT001',
        name: 'Amoxicilina Veterinaria 250mg',
        description: 'Antibiótico de amplio espectro - Caja x 20 tabletas',
        price: 45.00,
        cost: 22.00,
        stock: 40,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
        batches: [
          { id: 'b7', lotNumber: 'LOT-ANT-001', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      {
        id: '8',
        code: 'ANT002',
        name: 'Enrofloxacina 50mg',
        description: 'Antibiótico fluoroquinolona - Caja x 10 tabletas',
        price: 55.00,
        cost: 28.00,
        stock: 30,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
        batches: [
          { id: 'b8', lotNumber: 'LOT-ANT-002', expiryDate: nearExpiry, quantity: 30, isExpired: false },
        ],
      },
      // ========== ANTIINFLAMATORIOS ==========
      {
        id: '9',
        code: 'INF001',
        name: 'Meloxicam Veterinario 2mg',
        description: 'Antiinflamatorio no esteroideo - Caja x 10 tabletas',
        price: 38.00,
        cost: 18.00,
        stock: 50,
        unit: 'CAJA',
        category: 'cat-antiinflamatorios',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
        batches: [
          { id: 'b9', lotNumber: 'LOT-INF-001', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '10',
        code: 'INF002',
        name: 'Prednisolona 5mg',
        description: 'Corticosteroide - Caja x 20 tabletas',
        price: 42.00,
        cost: 20.00,
        stock: 35,
        unit: 'CAJA',
        category: 'cat-antiinflamatorios',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
        batches: [
          { id: 'b10', lotNumber: 'LOT-INF-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      // ========== ALIMENTOS ==========
      {
        id: '11',
        code: 'ALI001',
        name: 'Alimento Premium Perro Adulto 15kg',
        description: 'Alimento balanceado premium para perros adultos',
        price: 180.00,
        cost: 110.00,
        stock: 20,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b11', lotNumber: 'LOT-ALI-001', expiryDate: farExpiry, quantity: 20, isExpired: false },
        ],
      },
      {
        id: '12',
        code: 'ALI002',
        name: 'Alimento Premium Gato Adulto 8kg',
        description: 'Alimento balanceado premium para gatos adultos',
        price: 150.00,
        cost: 95.00,
        stock: 18,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b12', lotNumber: 'LOT-ALI-002', expiryDate: farExpiry, quantity: 18, isExpired: false },
        ],
      },
      {
        id: '13',
        code: 'ALI003',
        name: 'Alimento Medicado Renal Canino 3kg',
        description: 'Dieta especial para perros con problemas renales',
        price: 120.00,
        cost: 75.00,
        stock: 12,
        unit: 'BOLSA',
        category: 'cat-alimentos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b13', lotNumber: 'LOT-ALI-003', expiryDate: farExpiry, quantity: 12, isExpired: false },
        ],
      },
      // ========== ACCESORIOS ==========
      {
        id: '14',
        code: 'ACC001',
        name: 'Collar Ajustable Perro M',
        description: 'Collar de nylon ajustable para perros medianos',
        price: 25.00,
        cost: 12.00,
        stock: 30,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '15',
        code: 'ACC002',
        name: 'Correa Retráctil 5m',
        description: 'Correa retráctil para paseos',
        price: 45.00,
        cost: 22.00,
        stock: 20,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '16',
        code: 'ACC003',
        name: 'Cama para Mascota M',
        description: 'Cama acolchada lavable talla M',
        price: 85.00,
        cost: 45.00,
        stock: 15,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      // ========== HIGIENE ==========
      {
        id: '17',
        code: 'HIG001',
        name: 'Shampoo Antipulgas 500ml',
        description: 'Shampoo medicado antipulgas y garrapatas',
        price: 35.00,
        cost: 18.00,
        stock: 40,
        unit: 'FRASCO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b17', lotNumber: 'LOT-HIG-001', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      {
        id: '18',
        code: 'HIG002',
        name: 'Limpiador de Oídos 120ml',
        description: 'Solución limpiadora ótica para perros y gatos',
        price: 28.00,
        cost: 14.00,
        stock: 35,
        unit: 'FRASCO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b18', lotNumber: 'LOT-HIG-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      {
        id: '19',
        code: 'HIG003',
        name: 'Pasta Dental Veterinaria',
        description: 'Pasta dental sabor pollo para perros y gatos',
        price: 22.00,
        cost: 10.00,
        stock: 25,
        unit: 'TUBO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b19', lotNumber: 'LOT-HIG-003', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      // ========== SUPLEMENTOS ==========
      {
        id: '20',
        code: 'SUP001',
        name: 'Omega 3-6-9 para Mascotas',
        description: 'Suplemento para piel y pelo - Frasco x 60 cápsulas',
        price: 65.00,
        cost: 35.00,
        stock: 30,
        unit: 'FRASCO',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b20', lotNumber: 'LOT-SUP-001', expiryDate: farExpiry, quantity: 30, isExpired: false },
        ],
      },
      {
        id: '21',
        code: 'SUP002',
        name: 'Glucosamina + Condroitina',
        description: 'Suplemento para articulaciones - Frasco x 60 tabletas',
        price: 85.00,
        cost: 45.00,
        stock: 25,
        unit: 'FRASCO',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b21', lotNumber: 'LOT-SUP-002', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      {
        id: '22',
        code: 'SUP003',
        name: 'Probióticos Veterinarios',
        description: 'Suplemento digestivo - Caja x 30 sobres',
        price: 55.00,
        cost: 28.00,
        stock: 35,
        unit: 'CAJA',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b22', lotNumber: 'LOT-SUP-003', expiryDate: nearExpiry, quantity: 35, isExpired: false },
        ],
      },
    ],
    categories: [
      { id: 'cat-vacunas', name: 'Vacunas', parentId: null },
      { id: 'cat-antiparasitarios', name: 'Antiparasitarios', parentId: null },
      { id: 'cat-antibioticos', name: 'Antibióticos', parentId: null },
      { id: 'cat-antiinflamatorios', name: 'Antiinflamatorios', parentId: null },
      { id: 'cat-alimentos', name: 'Alimentos', parentId: null },
      { id: 'cat-accesorios', name: 'Accesorios', parentId: null },
      { id: 'cat-higiene', name: 'Higiene', parentId: null },
      { id: 'cat-suplementos', name: 'Suplementos', parentId: null },
    ],
    // Citas/Agenda
    appointments: [
      {
        id: 'apt1',
        petId: 'pet3',
        petName: 'Michi',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: tomorrow,
        time: '09:00',
        duration: 20,
        status: 'confirmed',
        notes: 'Vacuna Triple Felina - Primera dosis',
        veterinarian: 'Dr. Juan Pérez',
      },
      {
        id: 'apt2',
        petId: 'pet1',
        petName: 'Max',
        ownerName: 'María García López',
        ownerPhone: '987654321',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: nextWeek,
        time: '10:30',
        duration: 20,
        status: 'pending',
        notes: 'Refuerzo Séxtuple',
        veterinarian: 'Dra. Ana Rodríguez',
      },
      {
        id: 'apt3',
        petId: 'pet5',
        petName: 'Coco',
        ownerName: 'Pedro Ruiz Castro',
        ownerPhone: '987654324',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: nextWeek,
        time: '11:00',
        duration: 20,
        status: 'pending',
        notes: 'Vacuna antirrábica anual',
        veterinarian: 'Dr. Juan Pérez',
      },
      {
        id: 'apt4',
        petId: 'pet4',
        petName: 'Rocky',
        ownerName: 'Ana Torres Vega',
        ownerPhone: '987654323',
        service: 'Consulta General',
        serviceId: 'srv1',
        date: tomorrow,
        time: '15:00',
        duration: 30,
        status: 'confirmed',
        notes: 'Control de problemas respiratorios',
        veterinarian: 'Dra. Ana Rodríguez',
      },
      {
        id: 'apt5',
        petId: 'pet7',
        petName: 'Toby',
        ownerName: 'Rosa Mendez Luna',
        ownerPhone: '987654325',
        service: 'Baño y Corte',
        serviceId: 'srv4',
        date: inTwoWeeks,
        time: '09:00',
        duration: 60,
        status: 'pending',
        notes: 'Baño completo y corte de pelo',
        veterinarian: null,
      },
      {
        id: 'apt6',
        petId: 'pet2',
        petName: 'Luna',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: inTwoWeeks,
        time: '10:00',
        duration: 20,
        status: 'pending',
        notes: 'Triple Felina - Refuerzo anual',
        veterinarian: 'Dr. Juan Pérez',
      },
    ],
    // Alertas de vacunación
    vaccineAlerts: [
      {
        id: 'valert1',
        petId: 'pet3',
        petName: 'Michi',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        vaccineType: 'Triple Felina',
        dueDate: tomorrow,
        status: 'urgent',
        daysUntilDue: 1,
      },
      {
        id: 'valert2',
        petId: 'pet1',
        petName: 'Max',
        ownerName: 'María García López',
        ownerPhone: '987654321',
        vaccineType: 'Refuerzo Séxtuple',
        dueDate: nextWeek,
        status: 'upcoming',
        daysUntilDue: 7,
      },
      {
        id: 'valert3',
        petId: 'pet5',
        petName: 'Coco',
        ownerName: 'Pedro Ruiz Castro',
        ownerPhone: '987654324',
        vaccineType: 'Rabia',
        dueDate: nextWeek,
        status: 'upcoming',
        daysUntilDue: 7,
      },
      {
        id: 'valert4',
        petId: 'pet2',
        petName: 'Luna',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        vaccineType: 'Triple Felina',
        dueDate: inTwoWeeks,
        status: 'scheduled',
        daysUntilDue: 14,
      },
      {
        id: 'valert5',
        petId: 'pet7',
        petName: 'Toby',
        ownerName: 'Rosa Mendez Luna',
        ownerPhone: '987654325',
        vaccineType: 'Séxtuple + Rabia',
        dueDate: inTwoWeeks,
        status: 'scheduled',
        daysUntilDue: 14,
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '45678901', name: 'María García López', phone: '987654321' },
        items: [
          { code: 'SRV', description: 'Consulta General - Max', quantity: 1, price: 50.00 },
          { code: 'VAC001', description: 'Vacuna Séxtuple Canina', quantity: 1, price: 85.00 },
        ],
        subtotal: 135.00,
        tax: 24.30,
        total: 159.30,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 1),
      },
      {
        id: '2',
        number: 'B001-00000002',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '32165498', name: 'Carlos Mendoza Ríos', phone: '987654322' },
        items: [
          { code: 'SRV', description: 'Consulta General - Luna', quantity: 1, price: 50.00 },
          { code: 'PAR001', description: 'Desparasitante Interno', quantity: 1, price: 35.00 },
          { code: 'ALI002', description: 'Alimento Premium Gato 8kg', quantity: 1, price: 150.00 },
        ],
        subtotal: 235.00,
        tax: 42.30,
        total: 277.30,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 3),
      },
      {
        id: '3',
        number: 'B001-00000003',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '71234567', name: 'Ana Torres Vega', phone: '987654323' },
        items: [
          { code: 'SRV', description: 'Consulta General - Rocky', quantity: 1, price: 50.00 },
          { code: 'SRV', description: 'Rayos X', quantity: 1, price: 100.00 },
          { code: 'INF001', description: 'Meloxicam Veterinario', quantity: 1, price: 38.00 },
        ],
        subtotal: 188.00,
        tax: 33.84,
        total: 221.84,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '4',
        number: 'B001-00000004',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '72345678', name: 'Pedro Ruiz Castro', phone: '987654324' },
        items: [
          { code: 'SRV', description: 'Consulta General - Coco', quantity: 1, price: 50.00 },
          { code: 'SRV', description: 'Análisis de Sangre', quantity: 1, price: 80.00 },
          { code: 'ALI003', description: 'Alimento Medicado Renal', quantity: 1, price: 120.00 },
        ],
        subtotal: 250.00,
        tax: 45.00,
        total: 295.00,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 8),
      },
      {
        id: '5',
        number: 'B001-00000005',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '73456789', name: 'Rosa Mendez Luna', phone: '987654325' },
        items: [
          { code: 'SRV', description: 'Baño y Corte - Toby', quantity: 1, price: 60.00 },
          { code: 'HIG001', description: 'Shampoo Antipulgas', quantity: 1, price: 35.00 },
          { code: 'ACC001', description: 'Collar Ajustable M', quantity: 1, price: 25.00 },
        ],
        subtotal: 120.00,
        tax: 21.60,
        total: 141.60,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 10),
      },
      // Ventas del mes pasado
      {
        id: '6',
        number: 'B001-00000006',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '45678901', name: 'María García López', phone: '987654321' },
        items: [
          { code: 'PAR002', description: 'Pipeta Antipulgas', quantity: 2, price: 55.00 },
          { code: 'ALI001', description: 'Alimento Premium Perro 15kg', quantity: 1, price: 180.00 },
        ],
        subtotal: 290.00,
        tax: 52.20,
        total: 342.20,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 15),
      },
      {
        id: '7',
        number: 'B001-00000007',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '71234567', name: 'Ana Torres Vega', phone: '987654323' },
        items: [
          { code: 'SRV', description: 'Cirugía de Esterilización - Rocky', quantity: 1, price: 350.00 },
          { code: 'ANT001', description: 'Amoxicilina Veterinaria', quantity: 1, price: 45.00 },
          { code: 'INF001', description: 'Meloxicam Veterinario', quantity: 1, price: 38.00 },
        ],
        subtotal: 433.00,
        tax: 77.94,
        total: 510.94,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
      },
    ],
    suppliers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20123456789',
        businessName: 'DISTRIBUIDORA VETERINARIA DEL PERÚ SAC',
        contactName: 'Juan Rodríguez',
        email: 'ventas@distveterinaria.com',
        phone: '987111222',
        address: 'Av. Colonial 4567, Callao',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20234567890',
        businessName: 'LABORATORIOS VET PHARMA SAC',
        contactName: 'María González',
        email: 'compras@vetpharma.com',
        phone: '987222333',
        address: 'Av. Argentina 2020, Lima',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20345678901',
        businessName: 'ALIMENTOS MASCOTAS PERÚ EIRL',
        contactName: 'Carlos Pérez',
        email: 'ventas@alimentosmascotas.com',
        phone: '987333444',
        address: 'Av. Santa Rosa 390, Ate',
      },
    ],
    subscription: {
      status: 'active',
      plan: 'unlimited_12_months',
      currentPeriodEnd: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
      accessBlocked: false,
    },
    warehouses: [
      {
        id: '1',
        name: 'Almacén Principal',
        location: 'Av. La Marina 2580, San Miguel',
        isDefault: true,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
      {
        id: '2',
        name: 'Mostrador',
        location: 'Av. La Marina 2580, San Miguel',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
    ],
    expenses: [
      { id: 'exp1', date: new Date(today.getFullYear(), today.getMonth(), 5), description: 'Pago de luz del local', category: 'servicios', supplier: 'Luz del Sur', reference: 'REC-2024-001', paymentMethod: 'transferencia', amount: 320.00 },
      { id: 'exp2', date: new Date(today.getFullYear(), today.getMonth(), 8), description: 'Internet y teléfono', category: 'servicios', supplier: 'Movistar', reference: 'FAC-123456', paymentMethod: 'transferencia', amount: 180.00 },
      { id: 'exp3', date: new Date(today.getFullYear(), today.getMonth(), 15), description: 'Sueldos del mes', category: 'personal', supplier: '', reference: 'PLANILLA-ENE', paymentMethod: 'transferencia', amount: 8500.00 },
      { id: 'exp4', date: new Date(today.getFullYear(), today.getMonth(), 10), description: 'Alquiler del local', category: 'servicios', supplier: 'Inmobiliaria Central', reference: 'ALQ-ENE-2025', paymentMethod: 'transferencia', amount: 4500.00 },
    ],
  }
}

export const DemoVeterinaryProvider = ({ children }) => {
  const [demoData] = useState(generateVeterinaryDemoData())

  // Inyectar datos de demo en window para que los servicios puedan acceder
  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.__DEMO_DATA__ = demoData
    }
    return () => {
      if (typeof window !== 'undefined') {
        delete window.__DEMO_DATA__
      }
    }
  }, [demoData])

  const value = {
    isDemoMode: true,
    demoData,
  }

  return <DemoVeterinaryContext.Provider value={value}>{children}</DemoVeterinaryContext.Provider>
}

export const useDemoVeterinary = () => {
  const context = useContext(DemoVeterinaryContext)
  return context
}

export { DemoVeterinaryContext }
