import { createContext, useContext, useState } from 'react'

const DemoRestaurantContext = createContext(null)

// Datos de ejemplo para el demo de restaurante
const generateRestaurantDemoData = () => {
  const today = new Date()

  return {
    user: {
      uid: 'demo-restaurant-user',
      email: 'demo@restaurante.com',
      displayName: 'Usuario Demo Restaurante',
      photoURL: null,
    },
    business: {
      businessName: 'RESTAURANTE EL SABOR SAC',
      ruc: '20987654321',
      address: 'Av. La Marina 2355, San Miguel',
      phone: '01-5678901',
      email: 'contacto@elsabor.com',
      website: 'www.elsabor.com',
      mode: 'restaurant',
    },
    products: [
      {
        id: '1',
        code: 'PLT001',
        name: 'Ceviche de Pescado',
        description: 'Ceviche fresco del día',
        price: 32.00,
        cost: 15.00,
        stock: null,
        unit: 'PLATO',
        category: 'Entradas',
        hasVariants: false,
      },
      {
        id: '2',
        code: 'PLT002',
        name: 'Lomo Saltado',
        description: 'Lomo saltado con papas fritas y arroz',
        price: 28.00,
        cost: 12.00,
        stock: null,
        unit: 'PLATO',
        category: 'Platos de Fondo',
        hasVariants: false,
      },
      {
        id: '3',
        code: 'PLT003',
        name: 'Arroz con Pollo',
        description: 'Arroz con pollo y papa a la huancaína',
        price: 22.00,
        cost: 10.00,
        stock: null,
        unit: 'PLATO',
        category: 'Platos de Fondo',
        hasVariants: false,
      },
      {
        id: '4',
        code: 'PLT004',
        name: 'Ají de Gallina',
        description: 'Ají de gallina con arroz y papa',
        price: 24.00,
        cost: 11.00,
        stock: null,
        unit: 'PLATO',
        category: 'Platos de Fondo',
        hasVariants: false,
      },
      {
        id: '5',
        code: 'BEB001',
        name: 'Chicha Morada',
        description: 'Chicha morada natural (jarra)',
        price: 12.00,
        cost: 3.00,
        stock: null,
        unit: 'JARRA',
        category: 'Bebidas',
        hasVariants: false,
      },
      {
        id: '6',
        code: 'BEB002',
        name: 'Inca Kola',
        description: 'Inca Kola 500ml',
        price: 5.00,
        cost: 2.00,
        stock: 50,
        unit: 'UNIDAD',
        category: 'Bebidas',
        hasVariants: false,
      },
      {
        id: '7',
        code: 'PST001',
        name: 'Suspiro Limeño',
        description: 'Postre tradicional peruano',
        price: 12.00,
        cost: 5.00,
        stock: null,
        unit: 'PORCIÓN',
        category: 'Postres',
        hasVariants: false,
      },
      {
        id: '8',
        code: 'PLT005',
        name: 'Causa Limeña',
        description: 'Causa rellena de pollo',
        price: 18.00,
        cost: 8.00,
        stock: null,
        unit: 'PLATO',
        category: 'Entradas',
        hasVariants: false,
      },
    ],
    tables: [
      {
        id: '1',
        number: 1,
        capacity: 4,
        zone: 'Salón Principal',
        status: 'occupied',
        waiter: 'Carlos Rodríguez',
        waiterId: 'w1',
        startTime: new Date(today.setHours(today.getHours() - 1)),
        amount: 84.00,
        currentOrder: 'order1',
      },
      {
        id: '2',
        number: 2,
        capacity: 2,
        zone: 'Salón Principal',
        status: 'available',
      },
      {
        id: '3',
        number: 3,
        capacity: 6,
        zone: 'Salón Principal',
        status: 'occupied',
        waiter: 'María López',
        waiterId: 'w2',
        startTime: new Date(today.setHours(today.getHours() - 2)),
        amount: 156.00,
        currentOrder: 'order2',
      },
      {
        id: '4',
        number: 4,
        capacity: 4,
        zone: 'Terraza',
        status: 'reserved',
        reservedFor: '19:30',
        reservedBy: 'Juan Martínez',
        customerPhone: '987654321',
      },
      {
        id: '5',
        number: 5,
        capacity: 2,
        zone: 'Terraza',
        status: 'available',
      },
      {
        id: '6',
        number: 6,
        capacity: 4,
        zone: 'Terraza',
        status: 'available',
      },
      {
        id: '7',
        number: 7,
        capacity: 8,
        zone: 'Salón VIP',
        status: 'available',
      },
      {
        id: '8',
        number: 8,
        capacity: 4,
        zone: 'Salón Principal',
        status: 'occupied',
        waiter: 'Carlos Rodríguez',
        waiterId: 'w1',
        startTime: new Date(today.setMinutes(today.getMinutes() - 30)),
        amount: 46.00,
        currentOrder: 'order3',
      },
    ],
    waiters: [
      {
        id: 'w1',
        code: 'MOZ001',
        name: 'Carlos Rodríguez',
        phone: '987123456',
        status: 'active',
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'w2',
        code: 'MOZ002',
        name: 'María López',
        phone: '987123457',
        status: 'active',
        createdAt: new Date(2024, 0, 20),
      },
      {
        id: 'w3',
        code: 'MOZ003',
        name: 'Pedro García',
        phone: '987123458',
        status: 'active',
        createdAt: new Date(2024, 1, 5),
      },
    ],
    orders: [
      {
        id: 'order1',
        orderNumber: '#001',
        tableId: '1',
        tableNumber: 1,
        waiterName: 'Carlos Rodríguez',
        waiterId: 'w1',
        status: 'pending',
        items: [
          {
            productId: '1',
            name: 'Ceviche de Pescado',
            code: 'PLT001',
            price: 32.00,
            quantity: 2,
            total: 64.00,
          },
          {
            productId: '6',
            name: 'Inca Kola',
            code: 'BEB002',
            price: 5.00,
            quantity: 4,
            total: 20.00,
          },
        ],
        subtotal: 71.19,
        tax: 12.81,
        total: 84.00,
        createdAt: new Date(today.setHours(today.getHours() - 1)),
      },
      {
        id: 'order2',
        orderNumber: '#002',
        tableId: '3',
        tableNumber: 3,
        waiterName: 'María López',
        waiterId: 'w2',
        status: 'preparing',
        items: [
          {
            productId: '2',
            name: 'Lomo Saltado',
            code: 'PLT002',
            price: 28.00,
            quantity: 3,
            total: 84.00,
          },
          {
            productId: '3',
            name: 'Arroz con Pollo',
            code: 'PLT003',
            price: 22.00,
            quantity: 2,
            total: 44.00,
          },
          {
            productId: '5',
            name: 'Chicha Morada',
            code: 'BEB001',
            price: 12.00,
            quantity: 2,
            total: 24.00,
          },
        ],
        subtotal: 132.20,
        tax: 23.80,
        total: 156.00,
        createdAt: new Date(today.setHours(today.getHours() - 2)),
      },
      {
        id: 'order3',
        orderNumber: '#003',
        tableId: '8',
        tableNumber: 8,
        waiterName: 'Carlos Rodríguez',
        waiterId: 'w1',
        status: 'ready',
        items: [
          {
            productId: '8',
            name: 'Causa Limeña',
            code: 'PLT005',
            price: 18.00,
            quantity: 2,
            total: 36.00,
          },
          {
            productId: '6',
            name: 'Inca Kola',
            code: 'BEB002',
            price: 5.00,
            quantity: 2,
            total: 10.00,
          },
        ],
        subtotal: 38.98,
        tax: 7.02,
        total: 46.00,
        createdAt: new Date(today.setMinutes(today.getMinutes() - 30)),
      },
    ],
    customers: [
      {
        id: '1',
        documentType: '1',
        documentNumber: '45678901',
        name: 'María González',
        email: 'maria.gonzalez@email.com',
        phone: '987654321',
        address: 'Av. Universitaria 1234, San Miguel',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20123456789',
        name: 'EVENTOS Y CATERING SAC',
        email: 'eventos@catering.com',
        phone: '987654322',
        address: 'Jr. Comercio 567, Pueblo Libre',
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '45678901',
          name: 'María González',
          phone: '987654321',
          email: 'maria.gonzalez@email.com',
        },
        items: [
          {
            code: 'PLT002',
            description: 'Lomo Saltado',
            quantity: 2,
            price: 28.00,
          },
          {
            code: 'BEB001',
            description: 'Chicha Morada',
            quantity: 1,
            price: 12.00,
          },
        ],
        subtotal: 68.00,
        tax: 12.24,
        total: 80.24,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 10),
      },
    ],
    ingredients: [
      {
        id: 'ing1',
        name: 'Arroz',
        category: 'granos',
        purchaseUnit: 'kg',
        currentStock: 45.5,
        minimumStock: 10,
        averageCost: 3.80,
        lastPurchasePrice: 3.90,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing2',
        name: 'Pollo',
        category: 'carnes',
        purchaseUnit: 'kg',
        currentStock: 22.0,
        minimumStock: 8,
        averageCost: 12.50,
        lastPurchasePrice: 12.80,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing3',
        name: 'Papa',
        category: 'vegetales',
        purchaseUnit: 'kg',
        currentStock: 35.0,
        minimumStock: 15,
        averageCost: 2.50,
        lastPurchasePrice: 2.60,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing4',
        name: 'Pescado (filete)',
        category: 'carnes',
        purchaseUnit: 'kg',
        currentStock: 8.5,
        minimumStock: 5,
        averageCost: 18.00,
        lastPurchasePrice: 18.50,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing5',
        name: 'Limón',
        category: 'vegetales',
        purchaseUnit: 'kg',
        currentStock: 12.0,
        minimumStock: 3,
        averageCost: 4.50,
        lastPurchasePrice: 4.80,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing6',
        name: 'Cebolla Roja',
        category: 'vegetales',
        purchaseUnit: 'kg',
        currentStock: 18.0,
        minimumStock: 5,
        averageCost: 3.20,
        lastPurchasePrice: 3.50,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing7',
        name: 'Tomate',
        category: 'vegetales',
        purchaseUnit: 'kg',
        currentStock: 15.5,
        minimumStock: 5,
        averageCost: 3.80,
        lastPurchasePrice: 4.00,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing8',
        name: 'Aceite Vegetal',
        category: 'condimentos',
        purchaseUnit: 'L',
        currentStock: 8.0,
        minimumStock: 2,
        averageCost: 12.00,
        lastPurchasePrice: 12.50,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing9',
        name: 'Ají Amarillo (pasta)',
        category: 'condimentos',
        purchaseUnit: 'kg',
        currentStock: 3.2,
        minimumStock: 1,
        averageCost: 15.00,
        lastPurchasePrice: 15.50,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 6),
        createdAt: new Date(2024, 0, 15),
      },
      {
        id: 'ing10',
        name: 'Lomo de Res',
        category: 'carnes',
        purchaseUnit: 'kg',
        currentStock: 12.0,
        minimumStock: 5,
        averageCost: 22.00,
        lastPurchasePrice: 23.00,
        lastPurchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        createdAt: new Date(2024, 0, 15),
      },
    ],
    recipes: [
      {
        id: 'rec1',
        productId: '1',
        productName: 'Ceviche de Pescado',
        portions: 1,
        totalCost: 14.25,
        ingredients: [
          { ingredientId: 'ing4', ingredientName: 'Pescado (filete)', quantity: 0.25, unit: 'kg', cost: 4.50 },
          { ingredientId: 'ing5', ingredientName: 'Limón', quantity: 0.15, unit: 'kg', cost: 0.68 },
          { ingredientId: 'ing6', ingredientName: 'Cebolla Roja', quantity: 0.1, unit: 'kg', cost: 0.32 },
          { ingredientId: 'ing7', ingredientName: 'Tomate', quantity: 0.05, unit: 'kg', cost: 0.19 },
        ],
        createdAt: new Date(2024, 1, 10),
      },
      {
        id: 'rec2',
        productId: '2',
        productName: 'Lomo Saltado',
        portions: 1,
        totalCost: 11.85,
        ingredients: [
          { ingredientId: 'ing10', ingredientName: 'Lomo de Res', quantity: 0.22, unit: 'kg', cost: 4.84 },
          { ingredientId: 'ing3', ingredientName: 'Papa', quantity: 0.2, unit: 'kg', cost: 0.50 },
          { ingredientId: 'ing1', ingredientName: 'Arroz', quantity: 0.15, unit: 'kg', cost: 0.57 },
          { ingredientId: 'ing6', ingredientName: 'Cebolla Roja', quantity: 0.08, unit: 'kg', cost: 0.26 },
          { ingredientId: 'ing7', ingredientName: 'Tomate', quantity: 0.08, unit: 'kg', cost: 0.30 },
          { ingredientId: 'ing8', ingredientName: 'Aceite Vegetal', quantity: 0.05, unit: 'L', cost: 0.60 },
        ],
        createdAt: new Date(2024, 1, 10),
      },
      {
        id: 'rec3',
        productId: '3',
        productName: 'Arroz con Pollo',
        portions: 1,
        totalCost: 9.45,
        ingredients: [
          { ingredientId: 'ing2', ingredientName: 'Pollo', quantity: 0.25, unit: 'kg', cost: 3.13 },
          { ingredientId: 'ing1', ingredientName: 'Arroz', quantity: 0.2, unit: 'kg', cost: 0.76 },
          { ingredientId: 'ing3', ingredientName: 'Papa', quantity: 0.15, unit: 'kg', cost: 0.38 },
          { ingredientId: 'ing8', ingredientName: 'Aceite Vegetal', quantity: 0.03, unit: 'L', cost: 0.36 },
        ],
        createdAt: new Date(2024, 1, 10),
      },
      {
        id: 'rec4',
        productId: '4',
        productName: 'Ají de Gallina',
        portions: 1,
        totalCost: 10.60,
        ingredients: [
          { ingredientId: 'ing2', ingredientName: 'Pollo', quantity: 0.2, unit: 'kg', cost: 2.50 },
          { ingredientId: 'ing9', ingredientName: 'Ají Amarillo (pasta)', quantity: 0.08, unit: 'kg', cost: 1.20 },
          { ingredientId: 'ing1', ingredientName: 'Arroz', quantity: 0.15, unit: 'kg', cost: 0.57 },
          { ingredientId: 'ing3', ingredientName: 'Papa', quantity: 0.12, unit: 'kg', cost: 0.30 },
        ],
        createdAt: new Date(2024, 1, 10),
      },
      {
        id: 'rec5',
        productId: '8',
        productName: 'Causa Limeña',
        portions: 1,
        totalCost: 7.85,
        ingredients: [
          { ingredientId: 'ing3', ingredientName: 'Papa', quantity: 0.3, unit: 'kg', cost: 0.75 },
          { ingredientId: 'ing2', ingredientName: 'Pollo', quantity: 0.1, unit: 'kg', cost: 1.25 },
          { ingredientId: 'ing5', ingredientName: 'Limón', quantity: 0.05, unit: 'kg', cost: 0.23 },
          { ingredientId: 'ing9', ingredientName: 'Ají Amarillo (pasta)', quantity: 0.03, unit: 'kg', cost: 0.45 },
        ],
        createdAt: new Date(2024, 1, 10),
      },
    ],
    ingredientPurchases: [
      {
        id: 'pur1',
        ingredientId: 'ing1',
        ingredientName: 'Arroz',
        quantity: 50,
        unit: 'kg',
        unitPrice: 3.90,
        totalCost: 195.00,
        supplier: 'Distribuidora San Fernando',
        invoiceNumber: 'F001-12345',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
      },
      {
        id: 'pur2',
        ingredientId: 'ing2',
        ingredientName: 'Pollo',
        quantity: 25,
        unit: 'kg',
        unitPrice: 12.80,
        totalCost: 320.00,
        supplier: 'Avícola El Granjero',
        invoiceNumber: 'F001-54321',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
      },
      {
        id: 'pur3',
        ingredientId: 'ing4',
        ingredientName: 'Pescado (filete)',
        quantity: 10,
        unit: 'kg',
        unitPrice: 18.50,
        totalCost: 185.00,
        supplier: 'Pescadería El Puerto',
        invoiceNumber: 'B001-98765',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
      },
      {
        id: 'pur4',
        ingredientId: 'ing5',
        ingredientName: 'Limón',
        quantity: 15,
        unit: 'kg',
        unitPrice: 4.80,
        totalCost: 72.00,
        supplier: 'Mercado Mayorista',
        invoiceNumber: 'B001-11111',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
      },
      {
        id: 'pur5',
        ingredientId: 'ing3',
        ingredientName: 'Papa',
        quantity: 40,
        unit: 'kg',
        unitPrice: 2.60,
        totalCost: 104.00,
        supplier: 'Mercado Mayorista',
        invoiceNumber: 'B001-11112',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
      },
      {
        id: 'pur6',
        ingredientId: 'ing10',
        ingredientName: 'Lomo de Res',
        quantity: 15,
        unit: 'kg',
        unitPrice: 23.00,
        totalCost: 345.00,
        supplier: 'Carnes Premium SAC',
        invoiceNumber: 'F001-77777',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
      },
      {
        id: 'pur7',
        ingredientId: 'ing6',
        ingredientName: 'Cebolla Roja',
        quantity: 20,
        unit: 'kg',
        unitPrice: 3.50,
        totalCost: 70.00,
        supplier: 'Mercado Mayorista',
        invoiceNumber: 'B001-11113',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 4),
      },
      {
        id: 'pur8',
        ingredientId: 'ing8',
        ingredientName: 'Aceite Vegetal',
        quantity: 10,
        unit: 'L',
        unitPrice: 12.50,
        totalCost: 125.00,
        supplier: 'Distribuidora San Fernando',
        invoiceNumber: 'F001-12346',
        purchaseDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7),
      },
    ],
  }
}

export function DemoRestaurantProvider({ children }) {
  const [demoData] = useState(generateRestaurantDemoData())
  const [isDemo] = useState(true)

  const value = {
    ...demoData,
    isDemo,
    user: demoData.user,
    getBusinessId: () => 'demo-restaurant-user',
  }

  return (
    <DemoRestaurantContext.Provider value={value}>
      {children}
    </DemoRestaurantContext.Provider>
  )
}

export function useDemoRestaurant() {
  const context = useContext(DemoRestaurantContext)
  // No lanzar error si no está en el provider, simplemente retornar null
  // Esto permite usar el hook en cualquier lugar sin causar errores
  return context
}

export { DemoRestaurantContext }
