import { createContext, useContext, useState, useEffect } from 'react'

const DemoContext = createContext(null)

// Datos de ejemplo para el demo
const generateDemoData = () => {
  const today = new Date()
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1)
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)

  return {
    user: {
      uid: 'demo-user',
      email: 'demo@cobrifyperu.com',
      displayName: 'Usuario Demo',
      photoURL: null,
    },
    business: {
      businessName: 'EMPRESA DEMO SAC',
      ruc: '20123456789',
      address: 'Av. Larco 1234, Miraflores',
      phone: '01-2345678',
      email: 'ventas@empresademo.com',
      website: 'www.empresademo.com',
      logoUrl: '/demologo.png',
    },
    products: [
      // Productos de electrónica
      {
        id: '1',
        code: 'PROD001',
        name: 'Laptop HP 15"',
        description: 'Laptop HP 15 pulgadas, Intel Core i5, 8GB RAM',
        price: 2500.00,
        cost: 1800.00,
        stock: 15,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 10 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 5 },
        ],
      },
      {
        id: '2',
        code: 'PROD002',
        name: 'Mouse Inalámbrico',
        description: 'Mouse inalámbrico Logitech',
        price: 45.00,
        cost: 25.00,
        stock: 50,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 30 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 20 },
        ],
      },
      {
        id: '3',
        code: 'PROD003',
        name: 'Teclado Mecánico',
        description: 'Teclado mecánico RGB',
        price: 180.00,
        cost: 120.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 15 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 10 },
        ],
      },
      {
        id: '4',
        code: 'PROD004',
        name: 'Monitor 24"',
        description: 'Monitor LED 24 pulgadas Full HD',
        price: 650.00,
        cost: 450.00,
        stock: 12,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 8 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 4 },
        ],
      },
      // Productos de spa/belleza
      {
        id: '5',
        code: 'PROD005',
        name: 'Crema Hidratante Facial',
        description: 'Crema hidratante profesional para tratamientos faciales',
        price: 85.00,
        cost: 45.00,
        stock: 24,
        unit: 'UNIDAD',
        category: 'Belleza',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 24 },
        ],
      },
      {
        id: '6',
        code: 'PROD006',
        name: 'Aceite Esencial Lavanda',
        description: 'Aceite esencial puro para aromaterapia',
        price: 65.00,
        cost: 28.00,
        stock: 18,
        unit: 'UNIDAD',
        category: 'Belleza',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 18 },
        ],
      },
      // Más productos de electrónica
      {
        id: '7',
        code: 'PROD007',
        name: 'Audífonos Bluetooth',
        description: 'Audífonos inalámbricos con cancelación de ruido',
        price: 250.00,
        cost: 150.00,
        stock: 35,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 25 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 10 },
        ],
      },
      {
        id: '8',
        code: 'PROD008',
        name: 'Webcam HD 1080p',
        description: 'Cámara web Full HD con micrófono integrado',
        price: 180.00,
        cost: 95.00,
        stock: 28,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 20 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 8 },
        ],
      },
      {
        id: '9',
        code: 'PROD009',
        name: 'Hub USB 7 puertos',
        description: 'Hub USB 3.0 de 7 puertos con alimentación',
        price: 85.00,
        cost: 45.00,
        stock: 42,
        unit: 'UNIDAD',
        category: 'Electrónica',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 30 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 12 },
        ],
      },
      // Más productos de belleza
      {
        id: '10',
        code: 'PROD010',
        name: 'Mascarilla Facial',
        description: 'Mascarilla hidratante de colágeno',
        price: 35.00,
        cost: 12.00,
        stock: 60,
        unit: 'UNIDAD',
        category: 'Belleza',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 60 },
        ],
      },
      {
        id: '11',
        code: 'PROD011',
        name: 'Sérum Vitamina C',
        description: 'Sérum antioxidante con vitamina C pura',
        price: 95.00,
        cost: 38.00,
        stock: 32,
        unit: 'UNIDAD',
        category: 'Belleza',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 32 },
        ],
      },
      {
        id: '12',
        code: 'PROD012',
        name: 'Kit Manicure Profesional',
        description: 'Set completo de herramientas para manicure',
        price: 120.00,
        cost: 55.00,
        stock: 20,
        unit: 'UNIDAD',
        category: 'Belleza',
        hasVariants: false,
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 20 },
        ],
      },
      // Servicios
      {
        id: 'srv1',
        code: 'SERV001',
        name: 'Servicio de Instalación',
        description: 'Instalación de software y configuración',
        price: 120.00,
        cost: 0,
        stock: null,
        unit: 'SERVICIO',
        category: 'Servicios Técnicos',
        hasVariants: false,
      },
      {
        id: 'srv2',
        code: 'SERV002',
        name: 'Limpieza Facial Profunda',
        description: 'Tratamiento completo de limpieza facial con productos premium',
        price: 120.00,
        cost: 35.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'Servicios Spa',
        hasVariants: false,
        hasRecipe: true,
      },
      {
        id: 'srv3',
        code: 'SERV003',
        name: 'Masaje Relajante con Aromaterapia',
        description: 'Masaje de 60 minutos con aceites esenciales',
        price: 180.00,
        cost: 25.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'Servicios Spa',
        hasVariants: false,
        hasRecipe: true,
      },
      {
        id: 'srv4',
        code: 'SERV004',
        name: 'Mantenimiento de Equipos',
        description: 'Servicio de mantenimiento preventivo de computadoras',
        price: 150.00,
        cost: 30.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'Servicios Técnicos',
        hasVariants: false,
      },
    ],
    customers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20456789012',
        name: 'TECNOLOGÍA DEL PERÚ SAC',
        email: 'ventas@tecnologia.com',
        phone: '987654321',
        address: 'Av. Arequipa 2580, Lima',
      },
      {
        id: '2',
        documentType: '1',
        documentNumber: '45678901',
        name: 'Juan Pérez García',
        email: 'juan.perez@email.com',
        phone: '987654322',
        address: 'Jr. Cusco 456, San Isidro',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20567890123',
        name: 'COMERCIAL LIMA SRL',
        email: 'compras@comerciallima.com',
        phone: '987654323',
        address: 'Av. Venezuela 1234, Lima',
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '32165498',
        name: 'María Fernández López',
        email: 'maria.fernandez@email.com',
        phone: '987654324',
        address: 'Av. Larco 890, Miraflores',
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'F001-00000001',
        series: 'F001',
        documentType: 'factura',
        customer: {
          documentType: '6',
          documentNumber: '20456789012',
          name: 'TECNOLOGÍA DEL PERÚ SAC',
          phone: '987654321',
          email: 'ventas@tecnologia.com',
          address: 'Av. Arequipa 2580, Lima',
        },
        items: [
          {
            code: 'PROD001',
            description: 'Laptop HP 15"',
            quantity: 2,
            price: 2500.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 2,
            price: 45.00,
          },
        ],
        subtotal: 5090.00,
        tax: 916.20,
        total: 6006.20,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 15),
      },
      {
        id: '2',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '45678901',
          name: 'Juan Pérez García',
          phone: '987654322',
          email: 'juan.perez@email.com',
          address: 'Jr. Cusco 456, San Isidro',
        },
        items: [
          {
            code: 'PROD003',
            description: 'Teclado Mecánico',
            quantity: 1,
            price: 180.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 1,
            price: 45.00,
          },
        ],
        subtotal: 225.00,
        tax: 40.50,
        total: 265.50,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 18),
      },
      {
        id: '3',
        number: 'F001-00000002',
        series: 'F001',
        documentType: 'factura',
        customer: {
          documentType: '6',
          documentNumber: '20567890123',
          name: 'COMERCIAL LIMA SRL',
          phone: '987654323',
          email: 'compras@comerciallima.com',
          address: 'Av. Venezuela 1234, Lima',
        },
        items: [
          {
            code: 'PROD004',
            description: 'Monitor 24"',
            quantity: 5,
            price: 650.00,
          },
          {
            code: 'SERV001',
            description: 'Servicio de Instalación',
            quantity: 5,
            price: 120.00,
          },
        ],
        subtotal: 3850.00,
        tax: 693.00,
        total: 4543.00,
        status: 'pending',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 20),
      },
      {
        id: '4',
        number: 'B001-00000002',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '32165498',
          name: 'María Fernández López',
          phone: '987654324',
          email: 'maria.fernandez@email.com',
        },
        items: [
          {
            code: 'SERV002',
            description: 'Limpieza Facial Profunda',
            quantity: 1,
            price: 120.00,
          },
          {
            code: 'PROD005',
            description: 'Crema Hidratante Facial',
            quantity: 1,
            price: 85.00,
          },
        ],
        subtotal: 205.00,
        tax: 36.90,
        total: 241.90,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 22),
      },
      // Ventas del mes pasado
      {
        id: '5',
        number: 'B001-00000003',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '45678901',
          name: 'Juan Pérez García',
        },
        items: [
          {
            code: 'PROD001',
            description: 'Laptop HP 15"',
            quantity: 1,
            price: 2500.00,
          },
        ],
        subtotal: 2500.00,
        tax: 450.00,
        total: 2950.00,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
      },
      {
        id: '6',
        number: 'F001-00000003',
        series: 'F001',
        documentType: 'factura',
        customer: {
          documentType: '6',
          documentNumber: '20456789012',
          name: 'TECNOLOGÍA DEL PERÚ SAC',
        },
        items: [
          {
            code: 'PROD003',
            description: 'Teclado Mecánico',
            quantity: 10,
            price: 180.00,
          },
        ],
        subtotal: 1800.00,
        tax: 324.00,
        total: 2124.00,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 25),
      },
    ],
    quotations: [
      {
        id: '1',
        quotationNumber: 'COT001-00000001',
        series: 'COT001',
        customer: {
          documentType: '6',
          documentNumber: '20456789012',
          name: 'TECNOLOGÍA DEL PERÚ SAC',
          email: 'ventas@tecnologia.com',
          phone: '987654321',
          address: 'Av. Arequipa 2580, Lima',
        },
        items: [
          {
            code: 'PROD001',
            description: 'Laptop HP 15"',
            quantity: 3,
            price: 2500.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 3,
            price: 45.00,
          },
        ],
        subtotal: 7635.00,
        tax: 1374.30,
        total: 9009.30,
        status: 'pending',
        notes: 'Cotización válida por 15 días',
        validityDays: 15,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
        isSent: false,
        isConverted: false,
      },
      {
        id: '2',
        quotationNumber: 'COT001-00000002',
        series: 'COT001',
        customer: {
          documentType: '6',
          documentNumber: '20567890123',
          name: 'COMERCIAL LIMA SRL',
          email: 'compras@comerciallima.com',
          phone: '987654323',
          address: 'Av. Venezuela 1234, Lima',
        },
        items: [
          {
            code: 'PROD004',
            description: 'Monitor 24"',
            quantity: 10,
            price: 650.00,
          },
          {
            code: 'SERV001',
            description: 'Servicio de Instalación',
            quantity: 10,
            price: 120.00,
          },
        ],
        subtotal: 7700.00,
        tax: 1386.00,
        total: 9086.00,
        status: 'sent',
        notes: 'Incluye instalación y configuración',
        validityDays: 30,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 25),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        isSent: true,
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isConverted: false,
      },
      {
        id: '3',
        quotationNumber: 'COT001-00000003',
        series: 'COT001',
        customer: {
          documentType: '1',
          documentNumber: '32165498',
          name: 'María Fernández López',
          email: 'maria.fernandez@email.com',
          phone: '987654324',
          address: 'Av. Larco 890, Miraflores',
        },
        items: [
          {
            code: 'SERV002',
            description: 'Limpieza Facial Profunda',
            quantity: 4,
            price: 120.00,
          },
          {
            code: 'SERV003',
            description: 'Masaje Relajante con Aromaterapia',
            quantity: 4,
            price: 180.00,
          },
        ],
        subtotal: 1200.00,
        tax: 216.00,
        total: 1416.00,
        status: 'approved',
        notes: 'Paquete mensual de tratamientos spa',
        validityDays: 7,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isSent: true,
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isConverted: false,
      },
    ],
    suppliers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20123456789',
        businessName: 'DISTRIBUIDORA TECH SAC',
        contactName: 'Carlos Rodríguez',
        email: 'ventas@distribuidoratech.com',
        phone: '987123456',
        address: 'Av. Industrial 245, Ate',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20987654321',
        businessName: 'IMPORTACIONES GLOBAL SRL',
        contactName: 'María Fernández',
        email: 'compras@importacionesglobal.com',
        phone: '987123457',
        address: 'Jr. Comercio 890, Cercado de Lima',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20456789123',
        businessName: 'COSMÉTICOS NATURALES SAC',
        contactName: 'Laura Mendoza',
        email: 'ventas@cosmeticosnaturales.com',
        phone: '987123458',
        address: 'Av. Brasil 456, Jesús María',
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '43567890',
        businessName: 'SERVICIOS TÉCNICOS LÓPEZ',
        contactName: 'Luis López',
        email: 'luis.lopez@serviciotecnico.com',
        phone: '987123459',
        address: 'Av. Canadá 123, La Victoria',
      },
    ],
    purchases: [
      {
        id: '1',
        invoiceNumber: 'F001-00125',
        supplier: {
          id: '1',
          documentType: '6',
          documentNumber: '20123456789',
          businessName: 'DISTRIBUIDORA TECH SAC',
        },
        items: [
          {
            productId: '1',
            productName: 'Laptop HP 15"',
            quantity: 10,
            unitPrice: 1800.00,
          },
          {
            productId: '2',
            productName: 'Mouse Inalámbrico',
            quantity: 50,
            unitPrice: 25.00,
          },
        ],
        subtotal: 19250.00,
        igv: 3465.00,
        total: 22715.00,
        notes: 'Primera compra del mes',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '2',
        invoiceNumber: 'F001-00234',
        supplier: {
          id: '2',
          documentType: '6',
          documentNumber: '20987654321',
          businessName: 'IMPORTACIONES GLOBAL SRL',
        },
        items: [
          {
            productId: '4',
            productName: 'Monitor 24"',
            quantity: 20,
            unitPrice: 450.00,
          },
        ],
        subtotal: 9000.00,
        igv: 1620.00,
        total: 10620.00,
        notes: 'Compra de monitores para stock',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 12),
      },
      {
        id: '3',
        invoiceNumber: 'F002-00089',
        supplier: {
          id: '3',
          documentType: '6',
          documentNumber: '20456789123',
          businessName: 'COSMÉTICOS NATURALES SAC',
        },
        items: [
          {
            productId: '5',
            productName: 'Crema Hidratante Facial',
            quantity: 24,
            unitPrice: 45.00,
          },
          {
            productId: '6',
            productName: 'Aceite Esencial Lavanda',
            quantity: 18,
            unitPrice: 28.00,
          },
        ],
        subtotal: 1584.00,
        igv: 285.12,
        total: 1869.12,
        notes: 'Productos de belleza para stock',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 18),
      },
      // Compra del mes pasado
      {
        id: '4',
        invoiceNumber: 'F001-00098',
        supplier: {
          id: '1',
          documentType: '6',
          documentNumber: '20123456789',
          businessName: 'DISTRIBUIDORA TECH SAC',
        },
        items: [
          {
            productId: '3',
            productName: 'Teclado Mecánico',
            quantity: 30,
            unitPrice: 120.00,
          },
        ],
        subtotal: 3600.00,
        igv: 648.00,
        total: 4248.00,
        notes: 'Reposición de stock',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
      },
    ],
    subscription: {
      status: 'active',
      plan: 'unlimited_12_months',
      currentPeriodEnd: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
      accessBlocked: false,
    },
    warehouses: [
      {
        id: '1',
        name: 'Almacén Principal',
        location: 'Av. Larco 1234, Miraflores',
        isDefault: true,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 2, 1),
      },
      {
        id: '2',
        name: 'Almacén Secundario',
        location: 'Jr. Comercio 567, San Isidro',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 1, 15),
      },
      {
        id: '3',
        name: 'Almacén de Belleza',
        location: 'Av. Larco 1234, Miraflores',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
    ],
  }
}

export const DemoProvider = ({ children }) => {
  const [demoData] = useState(generateDemoData())

  // Inyectar datos de demo en window para que los servicios puedan acceder
  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.__DEMO_DATA__ = demoData
    }
    return () => {
      if (typeof window !== 'undefined') {
        delete window.__DEMO_DATA__
      }
    }
  }, [demoData])

  const value = {
    isDemoMode: true,
    demoData,
  }

  return <DemoContext.Provider value={value}>{children}</DemoContext.Provider>
}

export const useDemo = () => {
  const context = useContext(DemoContext)
  // No lanzar error si no está en un provider, simplemente retornar null
  // Esto permite usar el hook condicionalmente
  return context
}
