import { createContext, useContext, useState, useEffect } from 'react'

const DemoPharmacyContext = createContext(null)

// Datos de ejemplo para el demo de farmacia
const generatePharmacyDemoData = () => {
  const today = new Date()
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1)
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)

  // Fechas de vencimiento para productos
  const nearExpiry = new Date(today.getFullYear(), today.getMonth() + 1, 15) // próximo mes
  const expired = new Date(today.getFullYear(), today.getMonth() - 1, 10) // mes pasado
  const farExpiry = new Date(today.getFullYear() + 1, today.getMonth(), 1) // próximo año

  return {
    user: {
      uid: 'demo-pharmacy-user',
      email: 'demo@farmacia.com',
      displayName: 'Usuario Demo Farmacia',
      photoURL: null,
    },
    business: {
      businessName: 'FARMACIA SALUD TOTAL SAC',
      name: 'FARMACIA SALUD TOTAL SAC',
      ruc: '20567891234',
      address: 'Av. Brasil 1580, Jesús María',
      phone: '01-4567890',
      email: 'ventas@farmaciasaludtotal.com',
      website: 'www.farmaciasaludtotal.com',
      logoUrl: '/demologo.png',
      companySlogan: 'TU SALUD ES NUESTRA PRIORIDAD - MEDICAMENTOS, PRODUCTOS DE HIGIENE Y CUIDADO PERSONAL',
      mode: 'pharmacy',
    },
    laboratories: [
      { id: 'lab1', name: 'BAYER', country: 'Alemania', isActive: true },
      { id: 'lab2', name: 'PFIZER', country: 'Estados Unidos', isActive: true },
      { id: 'lab3', name: 'GENFAR', country: 'Colombia', isActive: true },
      { id: 'lab4', name: 'MEDIFARMA', country: 'Perú', isActive: true },
      { id: 'lab5', name: 'FARMINDUSTRIA', country: 'Perú', isActive: true },
      { id: 'lab6', name: 'ABBOTT', country: 'Estados Unidos', isActive: true },
      { id: 'lab7', name: 'ROCHE', country: 'Suiza', isActive: true },
      { id: 'lab8', name: 'JOHNSON & JOHNSON', country: 'Estados Unidos', isActive: true },
    ],
    products: [
      // ========== ANALGÉSICOS Y ANTIINFLAMATORIOS ==========
      {
        id: '1',
        code: 'MED001',
        name: 'Paracetamol 500mg Tabletas',
        description: 'Analgésico y antipirético - Caja x 100 tabletas',
        price: 8.50,
        cost: 4.00,
        stock: 200,
        unit: 'CAJA',
        category: 'cat-analgesicos',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 160 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 40 },
        ],
        batches: [
          { id: 'b1', lotNumber: 'LOT-2024-001', expiryDate: farExpiry, quantity: 150, isExpired: false },
          { id: 'b2', lotNumber: 'LOT-2024-002', expiryDate: nearExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '2',
        code: 'MED002',
        name: 'Ibuprofeno 400mg Tabletas',
        description: 'Antiinflamatorio no esteroideo - Caja x 50 tabletas',
        price: 12.00,
        cost: 6.00,
        stock: 120,
        unit: 'CAJA',
        category: 'cat-analgesicos',
        laboratoryId: 'lab3',
        laboratoryName: 'GENFAR',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 100 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 20 },
        ],
        batches: [
          { id: 'b3', lotNumber: 'LOT-2024-010', expiryDate: farExpiry, quantity: 120, isExpired: false },
        ],
      },
      {
        id: '3',
        code: 'MED003',
        name: 'Naproxeno 550mg Tabletas',
        description: 'Antiinflamatorio - Caja x 20 tabletas',
        price: 15.00,
        cost: 8.00,
        stock: 80,
        unit: 'CAJA',
        category: 'cat-analgesicos',
        laboratoryId: 'lab1',
        laboratoryName: 'BAYER',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 65 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b4', lotNumber: 'LOT-2024-015', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      // ========== ANTIBIÓTICOS ==========
      {
        id: '4',
        code: 'MED004',
        name: 'Amoxicilina 500mg Cápsulas',
        description: 'Antibiótico de amplio espectro - Caja x 21 cápsulas',
        price: 18.00,
        cost: 9.00,
        stock: 60,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        laboratoryId: 'lab5',
        laboratoryName: 'FARMINDUSTRIA',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 50 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b5', lotNumber: 'LOT-2024-020', expiryDate: farExpiry, quantity: 60, isExpired: false },
        ],
      },
      {
        id: '5',
        code: 'MED005',
        name: 'Azitromicina 500mg Tabletas',
        description: 'Antibiótico macrólido - Caja x 3 tabletas',
        price: 22.00,
        cost: 12.00,
        stock: 45,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        laboratoryId: 'lab2',
        laboratoryName: 'PFIZER',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 40 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 5 },
        ],
        batches: [
          { id: 'b6', lotNumber: 'LOT-2024-025', expiryDate: farExpiry, quantity: 45, isExpired: false },
        ],
      },
      {
        id: '6',
        code: 'MED006',
        name: 'Ciprofloxacino 500mg Tabletas',
        description: 'Antibiótico fluoroquinolona - Caja x 10 tabletas',
        price: 25.00,
        cost: 14.00,
        stock: 35,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        laboratoryId: 'lab1',
        laboratoryName: 'BAYER',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 30 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 5 },
        ],
        batches: [
          { id: 'b7', lotNumber: 'LOT-2024-030', expiryDate: nearExpiry, quantity: 35, isExpired: false },
        ],
      },
      // ========== JARABES ==========
      {
        id: '7',
        code: 'JAR001',
        name: 'Ambroxol Jarabe 120ml',
        description: 'Mucolítico expectorante - Frasco 120ml',
        price: 12.00,
        cost: 5.50,
        stock: 90,
        unit: 'FRASCO',
        category: 'cat-jarabes',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 75 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b8', lotNumber: 'LOT-2024-JAR01', expiryDate: farExpiry, quantity: 90, isExpired: false },
        ],
      },
      {
        id: '8',
        code: 'JAR002',
        name: 'Dextrometorfano Jarabe 120ml',
        description: 'Antitusígeno - Frasco 120ml',
        price: 14.00,
        cost: 7.00,
        stock: 70,
        unit: 'FRASCO',
        category: 'cat-jarabes',
        laboratoryId: 'lab3',
        laboratoryName: 'GENFAR',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 55 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b9', lotNumber: 'LOT-2024-JAR02', expiryDate: farExpiry, quantity: 70, isExpired: false },
        ],
      },
      {
        id: '9',
        code: 'JAR003',
        name: 'Paracetamol Infantil 60ml',
        description: 'Analgésico y antipirético pediátrico - Frasco 60ml',
        price: 10.00,
        cost: 4.50,
        stock: 100,
        unit: 'FRASCO',
        category: 'cat-jarabes',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 80 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 20 },
        ],
        batches: [
          { id: 'b10', lotNumber: 'LOT-2024-JAR03', expiryDate: farExpiry, quantity: 100, isExpired: false },
        ],
      },
      // ========== GASTRICOS ==========
      {
        id: '10',
        code: 'MED010',
        name: 'Omeprazol 20mg Cápsulas',
        description: 'Inhibidor de bomba de protones - Caja x 30 cápsulas',
        price: 15.00,
        cost: 7.00,
        stock: 85,
        unit: 'CAJA',
        category: 'cat-gastricos',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1626716493137-b67fe9501e76?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 70 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b11', lotNumber: 'LOT-2024-035', expiryDate: nearExpiry, quantity: 45, isExpired: false },
          { id: 'b12', lotNumber: 'LOT-2024-036', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      {
        id: '11',
        code: 'MED011',
        name: 'Ranitidina 150mg Tabletas',
        description: 'Antiulceroso - Caja x 20 tabletas',
        price: 8.00,
        cost: 3.50,
        stock: 60,
        unit: 'CAJA',
        category: 'cat-gastricos',
        laboratoryId: 'lab3',
        laboratoryName: 'GENFAR',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 50 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b13', lotNumber: 'LOT-2024-040', expiryDate: farExpiry, quantity: 60, isExpired: false },
        ],
      },
      {
        id: '12',
        code: 'MED012',
        name: 'Sal de Andrews Sobres',
        description: 'Antiácido efervescente - Caja x 50 sobres',
        price: 18.00,
        cost: 9.00,
        stock: 75,
        unit: 'CAJA',
        category: 'cat-gastricos',
        laboratoryId: 'lab6',
        laboratoryName: 'ABBOTT',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 60 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b14', lotNumber: 'LOT-2024-045', expiryDate: farExpiry, quantity: 75, isExpired: false },
        ],
      },
      // ========== ANTIALÉRGICOS ==========
      {
        id: '13',
        code: 'MED013',
        name: 'Loratadina 10mg Tabletas',
        description: 'Antihistamínico - Caja x 30 tabletas',
        price: 10.00,
        cost: 4.50,
        stock: 65,
        unit: 'CAJA',
        category: 'cat-alergias',
        laboratoryId: 'lab1',
        laboratoryName: 'BAYER',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 55 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b15', lotNumber: 'LOT-2024-050', expiryDate: farExpiry, quantity: 65, isExpired: false },
        ],
      },
      {
        id: '14',
        code: 'MED014',
        name: 'Cetirizina 10mg Tabletas',
        description: 'Antihistamínico - Caja x 30 tabletas',
        price: 12.00,
        cost: 5.50,
        stock: 50,
        unit: 'CAJA',
        category: 'cat-alergias',
        laboratoryId: 'lab2',
        laboratoryName: 'PFIZER',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 40 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b16', lotNumber: 'LOT-2024-055', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      // ========== GOTAS OFTÁLMICAS ==========
      {
        id: '15',
        code: 'OFT001',
        name: 'Lágrimas Artificiales 15ml',
        description: 'Lubricante ocular - Frasco 15ml',
        price: 18.00,
        cost: 9.00,
        stock: 55,
        unit: 'FRASCO',
        category: 'cat-oftalmicos',
        laboratoryId: 'lab6',
        laboratoryName: 'ABBOTT',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 45 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b17', lotNumber: 'LOT-2024-OFT01', expiryDate: farExpiry, quantity: 55, isExpired: false },
        ],
      },
      {
        id: '16',
        code: 'OFT002',
        name: 'Tobramicina Gotas 5ml',
        description: 'Antibiótico oftálmico - Frasco 5ml',
        price: 25.00,
        cost: 14.00,
        stock: 30,
        unit: 'FRASCO',
        category: 'cat-oftalmicos',
        laboratoryId: 'lab5',
        laboratoryName: 'FARMINDUSTRIA',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 25 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 5 },
        ],
        batches: [
          { id: 'b18', lotNumber: 'LOT-2024-OFT02', expiryDate: nearExpiry, quantity: 30, isExpired: false },
        ],
      },
      // ========== VITAMINAS Y SUPLEMENTOS ==========
      {
        id: '17',
        code: 'VIT001',
        name: 'Vitamina C 1000mg Tabletas',
        description: 'Suplemento vitamínico - Frasco x 60 tabletas',
        price: 28.00,
        cost: 14.00,
        stock: 80,
        unit: 'FRASCO',
        category: 'cat-vitaminas',
        laboratoryId: 'lab6',
        laboratoryName: 'ABBOTT',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 65 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b19', lotNumber: 'LOT-2024-VIT01', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      {
        id: '18',
        code: 'VIT002',
        name: 'Complejo B Tabletas',
        description: 'Vitaminas B1, B6, B12 - Frasco x 100 tabletas',
        price: 22.00,
        cost: 11.00,
        stock: 70,
        unit: 'FRASCO',
        category: 'cat-vitaminas',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 55 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b20', lotNumber: 'LOT-2024-VIT02', expiryDate: nearExpiry, quantity: 40, isExpired: false },
          { id: 'b21', lotNumber: 'LOT-2024-VIT03', expiryDate: farExpiry, quantity: 30, isExpired: false },
        ],
      },
      {
        id: '19',
        code: 'VIT003',
        name: 'Ácido Fólico 1mg Tabletas',
        description: 'Suplemento prenatal - Caja x 30 tabletas',
        price: 8.00,
        cost: 3.50,
        stock: 90,
        unit: 'CAJA',
        category: 'cat-vitaminas',
        laboratoryId: 'lab3',
        laboratoryName: 'GENFAR',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 75 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b22', lotNumber: 'LOT-2024-VIT04', expiryDate: farExpiry, quantity: 90, isExpired: false },
        ],
      },
      {
        id: '20',
        code: 'VIT004',
        name: 'Hierro + Ácido Fólico Tabletas',
        description: 'Suplemento antianémico - Caja x 30 tabletas',
        price: 12.00,
        cost: 5.50,
        stock: 65,
        unit: 'CAJA',
        category: 'cat-vitaminas',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 50 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b23', lotNumber: 'LOT-2024-VIT05', expiryDate: farExpiry, quantity: 65, isExpired: false },
        ],
      },
      // ========== CREMAS Y UNGÜENTOS ==========
      {
        id: '21',
        code: 'CRE001',
        name: 'Clotrimazol Crema 1% 20g',
        description: 'Antimicótico tópico - Tubo 20g',
        price: 10.00,
        cost: 4.50,
        stock: 55,
        unit: 'TUBO',
        category: 'cat-cremas',
        laboratoryId: 'lab1',
        laboratoryName: 'BAYER',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 45 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b24', lotNumber: 'LOT-2024-CRE01', expiryDate: farExpiry, quantity: 55, isExpired: false },
        ],
      },
      {
        id: '22',
        code: 'CRE002',
        name: 'Diclofenaco Gel 1% 50g',
        description: 'Antiinflamatorio tópico - Tubo 50g',
        price: 18.00,
        cost: 9.00,
        stock: 45,
        unit: 'TUBO',
        category: 'cat-cremas',
        laboratoryId: 'lab3',
        laboratoryName: 'GENFAR',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 35 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b25', lotNumber: 'LOT-2024-CRE02', expiryDate: farExpiry, quantity: 45, isExpired: false },
        ],
      },
      {
        id: '23',
        code: 'CRE003',
        name: 'Betametasona Crema 0.05% 15g',
        description: 'Corticoide tópico - Tubo 15g',
        price: 12.00,
        cost: 5.50,
        stock: 40,
        unit: 'TUBO',
        category: 'cat-cremas',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 32 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 8 },
        ],
        batches: [
          { id: 'b26', lotNumber: 'LOT-2024-CRE03', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      // ========== PRODUCTOS DE HIGIENE ==========
      {
        id: '24',
        code: 'HIG001',
        name: 'Alcohol en Gel 500ml',
        description: 'Desinfectante de manos - Frasco 500ml',
        price: 15.00,
        cost: 7.00,
        stock: 120,
        unit: 'FRASCO',
        category: 'cat-higiene',
        laboratoryId: 'lab8',
        laboratoryName: 'JOHNSON & JOHNSON',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 100 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 20 },
        ],
        batches: [
          { id: 'b27', lotNumber: 'LOT-2024-HIG01', expiryDate: farExpiry, quantity: 120, isExpired: false },
        ],
      },
      {
        id: '25',
        code: 'HIG002',
        name: 'Alcohol Medicinal 70° 1L',
        description: 'Alcohol para desinfección - Frasco 1 Litro',
        price: 12.00,
        cost: 5.50,
        stock: 80,
        unit: 'FRASCO',
        category: 'cat-higiene',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 65 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b28', lotNumber: 'LOT-2024-HIG02', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      {
        id: '26',
        code: 'HIG003',
        name: 'Agua Oxigenada 120ml',
        description: 'Antiséptico - Frasco 120ml',
        price: 5.00,
        cost: 2.00,
        stock: 100,
        unit: 'FRASCO',
        category: 'cat-higiene',
        laboratoryId: 'lab4',
        laboratoryName: 'MEDIFARMA',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 85 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b29', lotNumber: 'LOT-2024-HIG03', expiryDate: farExpiry, quantity: 100, isExpired: false },
        ],
      },
      // ========== PRODUCTOS VARIOS CON VENCIMIENTOS PRÓXIMOS O VENCIDOS ==========
      {
        id: '27',
        code: 'MED027',
        name: 'Aspirina 100mg Tabletas',
        description: 'Antiagregante plaquetario - Caja x 100 tabletas',
        price: 8.00,
        cost: 3.50,
        stock: 30,
        unit: 'CAJA',
        category: 'cat-cardiovascular',
        laboratoryId: 'lab1',
        laboratoryName: 'BAYER',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 25 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 5 },
        ],
        batches: [
          { id: 'b30', lotNumber: 'LOT-2023-EXP01', expiryDate: expired, quantity: 10, isExpired: true },
          { id: 'b31', lotNumber: 'LOT-2024-060', expiryDate: farExpiry, quantity: 20, isExpired: false },
        ],
      },
      // ========== PRODUCTOS PARA BEBÉS ==========
      {
        id: '28',
        code: 'BB001',
        name: 'Pañales Huggies Talla M',
        description: 'Pañales desechables - Paquete x 40 unidades',
        price: 45.00,
        cost: 28.00,
        stock: 50,
        unit: 'PAQUETE',
        category: 'cat-bebes',
        laboratoryId: 'lab8',
        laboratoryName: 'JOHNSON & JOHNSON',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 40 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b32', lotNumber: 'LOT-2024-BB01', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '29',
        code: 'BB002',
        name: 'Crema Antipañalitis 60g',
        description: 'Protector de piel para bebés - Tubo 60g',
        price: 18.00,
        cost: 9.00,
        stock: 40,
        unit: 'TUBO',
        category: 'cat-bebes',
        laboratoryId: 'lab8',
        laboratoryName: 'JOHNSON & JOHNSON',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 32 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 8 },
        ],
        batches: [
          { id: 'b33', lotNumber: 'LOT-2024-BB02', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      // ========== MATERIAL MÉDICO ==========
      {
        id: '30',
        code: 'MAT001',
        name: 'Algodón 100g',
        description: 'Algodón hidrófilo - Bolsa 100g',
        price: 6.00,
        cost: 2.50,
        stock: 80,
        unit: 'BOLSA',
        category: 'cat-material-medico',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 65 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b34', lotNumber: 'LOT-2024-MAT01', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      {
        id: '31',
        code: 'MAT002',
        name: 'Gasas Estériles 10x10',
        description: 'Gasas estériles - Caja x 100 unidades',
        price: 15.00,
        cost: 7.00,
        stock: 60,
        unit: 'CAJA',
        category: 'cat-material-medico',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 50 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 10 },
        ],
        batches: [
          { id: 'b35', lotNumber: 'LOT-2024-MAT02', expiryDate: farExpiry, quantity: 60, isExpired: false },
        ],
      },
      {
        id: '32',
        code: 'MAT003',
        name: 'Vendas Elásticas 4"',
        description: 'Vendas elásticas - Unidad',
        price: 8.00,
        cost: 3.50,
        stock: 45,
        unit: 'UNIDAD',
        category: 'cat-material-medico',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 38 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 7 },
        ],
        batches: [
          { id: 'b36', lotNumber: 'LOT-2024-MAT03', expiryDate: farExpiry, quantity: 45, isExpired: false },
        ],
      },
      {
        id: '33',
        code: 'MAT004',
        name: 'Curitas Adhesivas x100',
        description: 'Apósitos adhesivos - Caja x 100 unidades',
        price: 12.00,
        cost: 5.00,
        stock: 70,
        unit: 'CAJA',
        category: 'cat-material-medico',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 55 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 15 },
        ],
        batches: [
          { id: 'b37', lotNumber: 'LOT-2024-MAT04', expiryDate: farExpiry, quantity: 70, isExpired: false },
        ],
      },
      {
        id: '34',
        code: 'MAT005',
        name: 'Jeringas 5ml x100',
        description: 'Jeringas descartables - Caja x 100 unidades',
        price: 25.00,
        cost: 12.00,
        stock: 30,
        unit: 'CAJA',
        category: 'cat-material-medico',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 25 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 5 },
        ],
        batches: [
          { id: 'b38', lotNumber: 'LOT-2024-MAT05', expiryDate: farExpiry, quantity: 30, isExpired: false },
        ],
      },
      // ========== CUIDADO PERSONAL ==========
      {
        id: '35',
        code: 'PER001',
        name: 'Protector Solar SPF50 120ml',
        description: 'Protección solar - Frasco 120ml',
        price: 45.00,
        cost: 25.00,
        stock: 35,
        unit: 'FRASCO',
        category: 'cat-cuidado-personal',
        laboratoryId: 'lab7',
        laboratoryName: 'ROCHE',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 28 },
          { warehouseId: '2', warehouseName: 'Mostrador', stock: 7 },
        ],
        batches: [
          { id: 'b39', lotNumber: 'LOT-2024-PER01', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
    ],
    categories: [
      { id: 'cat-analgesicos', name: 'Analgésicos y Antiinflamatorios', parentId: null },
      { id: 'cat-antibioticos', name: 'Antibióticos', parentId: null },
      { id: 'cat-jarabes', name: 'Jarabes y Suspensiones', parentId: null },
      { id: 'cat-gastricos', name: 'Protectores Gástricos', parentId: null },
      { id: 'cat-alergias', name: 'Antialérgicos', parentId: null },
      { id: 'cat-oftalmicos', name: 'Oftálmicos', parentId: null },
      { id: 'cat-vitaminas', name: 'Vitaminas y Suplementos', parentId: null },
      { id: 'cat-cremas', name: 'Cremas y Ungüentos', parentId: null },
      { id: 'cat-higiene', name: 'Higiene y Desinfección', parentId: null },
      { id: 'cat-cardiovascular', name: 'Cardiovascular', parentId: null },
      { id: 'cat-bebes', name: 'Bebés y Niños', parentId: null },
      { id: 'cat-material-medico', name: 'Material Médico', parentId: null },
      { id: 'cat-cuidado-personal', name: 'Cuidado Personal', parentId: null },
    ],
    customers: [
      {
        id: '1',
        documentType: '1',
        documentNumber: '45678901',
        name: 'María García López',
        email: 'maria.garcia@email.com',
        phone: '987654321',
        address: 'Av. Salaverry 1234, Jesús María',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20456789012',
        name: 'CLINICA SAN PABLO SAC',
        email: 'compras@clinicasanpablo.com',
        phone: '987654322',
        address: 'Av. El Polo 789, Surco',
      },
      {
        id: '3',
        documentType: '1',
        documentNumber: '32165498',
        name: 'Carlos Mendoza Ríos',
        email: 'carlos.mendoza@email.com',
        phone: '987654323',
        address: 'Jr. Camaná 456, Cercado de Lima',
      },
      {
        id: '4',
        documentType: '6',
        documentNumber: '20567890123',
        name: 'BOTICA POPULAR EIRL',
        email: 'pedidos@boticapopular.com',
        phone: '987654324',
        address: 'Av. Abancay 890, Lima',
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '45678901',
          name: 'María García López',
          phone: '987654321',
          email: 'maria.garcia@email.com',
        },
        items: [
          { code: 'MED001', description: 'Paracetamol 500mg', quantity: 2, price: 12.00 },
          { code: 'MED004', description: 'Omeprazol 20mg', quantity: 1, price: 18.00 },
        ],
        subtotal: 42.00,
        tax: 7.56,
        total: 49.56,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 1),
      },
      { id: '2', number: 'B001-00000002', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '32165498', name: 'Carlos Mendoza Ríos' }, items: [{ code: 'MED002', description: 'Ibuprofeno 400mg', quantity: 1, price: 15.00 }, { code: 'VIT001', description: 'Vitamina C 1000mg', quantity: 1, price: 35.00 }], subtotal: 50.00, tax: 9.00, total: 59.00, status: 'paid', paymentMethod: 'Tarjeta', createdAt: new Date(today.getFullYear(), today.getMonth(), 2) },
      { id: '3', number: 'F001-00000001', series: 'F001', documentType: 'factura', customer: { documentType: '6', documentNumber: '20456789012', name: 'CLINICA SAN PABLO SAC' }, items: [{ code: 'MED003', description: 'Amoxicilina 500mg', quantity: 20, price: 25.00 }, { code: 'MED001', description: 'Paracetamol 500mg', quantity: 50, price: 12.00 }, { code: 'HIG001', description: 'Alcohol en Gel 500ml', quantity: 30, price: 15.00 }], subtotal: 1550.00, tax: 279.00, total: 1829.00, status: 'paid', paymentMethod: 'Transferencia', createdAt: new Date(today.getFullYear(), today.getMonth(), 3) },
      { id: '4', number: 'B001-00000003', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '71234567', name: 'Ana Torres Vega' }, items: [{ code: 'BB001', description: 'Pañales Bebé Talla M', quantity: 2, price: 48.00 }, { code: 'HIG001', description: 'Alcohol en Gel 500ml', quantity: 1, price: 15.00 }], subtotal: 111.00, tax: 19.98, total: 130.98, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(today.getFullYear(), today.getMonth(), 4) },
      { id: '5', number: 'B001-00000004', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '72345678', name: 'Pedro Ruiz Castro' }, items: [{ code: 'MED005', description: 'Loratadina 10mg', quantity: 1, price: 12.00 }, { code: 'PER001', description: 'Protector Solar SPF50', quantity: 1, price: 55.00 }], subtotal: 67.00, tax: 12.06, total: 79.06, status: 'paid', paymentMethod: 'Tarjeta', createdAt: new Date(today.getFullYear(), today.getMonth(), 5) },
      { id: '6', number: 'F001-00000002', series: 'F001', documentType: 'factura', customer: { documentType: '6', documentNumber: '20567890123', name: 'BOTICA POPULAR EIRL' }, items: [{ code: 'MED001', description: 'Paracetamol 500mg', quantity: 100, price: 12.00 }, { code: 'MED002', description: 'Ibuprofeno 400mg', quantity: 50, price: 15.00 }, { code: 'MED004', description: 'Omeprazol 20mg', quantity: 30, price: 18.00 }], subtotal: 2490.00, tax: 448.20, total: 2938.20, status: 'paid', paymentMethod: 'Transferencia', createdAt: new Date(today.getFullYear(), today.getMonth(), 6) },
      { id: '7', number: 'B001-00000005', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '73456789', name: 'Rosa Mendez Luna' }, items: [{ code: 'VIT002', description: 'Complejo B', quantity: 2, price: 28.00 }, { code: 'MED006', description: 'Aspirina 100mg', quantity: 1, price: 8.00 }], subtotal: 64.00, tax: 11.52, total: 75.52, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(today.getFullYear(), today.getMonth(), 7) },
      { id: '8', number: 'B001-00000006', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '74567890', name: 'Luis Paredes Soto' }, items: [{ code: 'HIG002', description: 'Mascarillas KN95', quantity: 1, price: 45.00 }, { code: 'HIG001', description: 'Alcohol en Gel 500ml', quantity: 2, price: 15.00 }], subtotal: 75.00, tax: 13.50, total: 88.50, status: 'paid', paymentMethod: 'Tarjeta', createdAt: new Date(today.getFullYear(), today.getMonth(), 8) },
      { id: '9', number: 'B001-00000007', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '75678901', name: 'Carmen Flores Díaz' }, items: [{ code: 'MED001', description: 'Paracetamol 500mg', quantity: 1, price: 12.00 }, { code: 'MED002', description: 'Ibuprofeno 400mg', quantity: 1, price: 15.00 }, { code: 'VIT001', description: 'Vitamina C 1000mg', quantity: 1, price: 35.00 }], subtotal: 62.00, tax: 11.16, total: 73.16, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(today.getFullYear(), today.getMonth(), 9) },
      { id: '10', number: 'F001-00000003', series: 'F001', documentType: 'factura', customer: { documentType: '6', documentNumber: '20456789012', name: 'CLINICA SAN PABLO SAC' }, items: [{ code: 'MED003', description: 'Amoxicilina 500mg', quantity: 30, price: 25.00 }, { code: 'VIT001', description: 'Vitamina C 1000mg', quantity: 50, price: 35.00 }], subtotal: 2500.00, tax: 450.00, total: 2950.00, status: 'paid', paymentMethod: 'Transferencia', createdAt: new Date(today.getFullYear(), today.getMonth(), 10) },
      { id: '11', number: 'B001-00000008', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '76789012', name: 'Jorge Quispe Mamani' }, items: [{ code: 'MED004', description: 'Omeprazol 20mg', quantity: 2, price: 18.00 }, { code: 'MED005', description: 'Loratadina 10mg', quantity: 1, price: 12.00 }], subtotal: 48.00, tax: 8.64, total: 56.64, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(today.getFullYear(), today.getMonth(), 11) },
      { id: '12', number: 'B001-00000009', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '77890123', name: 'Sofía Ramos Huanca' }, items: [{ code: 'BB001', description: 'Pañales Bebé Talla M', quantity: 3, price: 48.00 }, { code: 'PER001', description: 'Protector Solar SPF50', quantity: 1, price: 55.00 }], subtotal: 199.00, tax: 35.82, total: 234.82, status: 'paid', paymentMethod: 'Tarjeta', createdAt: new Date(today.getFullYear(), today.getMonth(), 12) },
      // Ventas del mes pasado
      { id: '13', number: 'B001-00000010', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '78901234', name: 'Miguel Vargas Peña' }, items: [{ code: 'MED001', description: 'Paracetamol 500mg', quantity: 3, price: 12.00 }], subtotal: 36.00, tax: 6.48, total: 42.48, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 5) },
      { id: '14', number: 'F001-00000004', series: 'F001', documentType: 'factura', customer: { documentType: '6', documentNumber: '20567890123', name: 'BOTICA POPULAR EIRL' }, items: [{ code: 'MED002', description: 'Ibuprofeno 400mg', quantity: 80, price: 15.00 }, { code: 'MED005', description: 'Loratadina 10mg', quantity: 40, price: 12.00 }], subtotal: 1680.00, tax: 302.40, total: 1982.40, status: 'paid', paymentMethod: 'Transferencia', createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10) },
      { id: '15', number: 'B001-00000011', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '79012345', name: 'Elena Castro Vera' }, items: [{ code: 'VIT002', description: 'Complejo B', quantity: 1, price: 28.00 }, { code: 'VIT001', description: 'Vitamina C 1000mg', quantity: 1, price: 35.00 }], subtotal: 63.00, tax: 11.34, total: 74.34, status: 'paid', paymentMethod: 'Tarjeta', createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 15) },
      { id: '16', number: 'B001-00000012', series: 'B001', documentType: 'boleta', customer: { documentType: '1', documentNumber: '80123456', name: 'Ricardo Luna Torres' }, items: [{ code: 'HIG001', description: 'Alcohol en Gel 500ml', quantity: 4, price: 15.00 }, { code: 'HIG002', description: 'Mascarillas KN95', quantity: 2, price: 45.00 }], subtotal: 150.00, tax: 27.00, total: 177.00, status: 'paid', paymentMethod: 'Efectivo', createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20) },
    ],
    suppliers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20123456789',
        businessName: 'DISTRIBUIDORA FARMACÉUTICA DEL PERÚ SAC',
        contactName: 'Juan Rodríguez',
        email: 'ventas@disfarperu.com',
        phone: '987111222',
        address: 'Av. Colonial 4567, Callao',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20234567890',
        businessName: 'QUÍMICA SUIZA SAC',
        contactName: 'María González',
        email: 'compras@quimicasuiza.com',
        phone: '987222333',
        address: 'Av. República de Panamá 3535, San Isidro',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20345678901',
        businessName: 'MEDIFARMA SAC',
        contactName: 'Carlos Pérez',
        email: 'ventas@medifarma.com',
        phone: '987333444',
        address: 'Av. Santa Rosa 390, Ate',
      },
    ],
    purchases: [
      {
        id: '1',
        invoiceNumber: 'F001-00345',
        supplier: {
          id: '1',
          documentType: '6',
          documentNumber: '20123456789',
          businessName: 'DISTRIBUIDORA FARMACÉUTICA DEL PERÚ SAC',
        },
        items: [
          { productId: '1', productName: 'Paracetamol 500mg', quantity: 100, unitPrice: 6.50, lotNumber: 'LOT-2024-001', expiryDate: farExpiry },
          { productId: '2', productName: 'Ibuprofeno 400mg', quantity: 50, unitPrice: 8.00, lotNumber: 'LOT-2024-010', expiryDate: farExpiry },
        ],
        subtotal: 1050.00,
        igv: 189.00,
        total: 1239.00,
        notes: 'Reposición mensual de analgésicos',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '2',
        invoiceNumber: 'F001-00567',
        supplier: {
          id: '3',
          documentType: '6',
          documentNumber: '20345678901',
          businessName: 'MEDIFARMA SAC',
        },
        items: [
          { productId: '4', productName: 'Omeprazol 20mg', quantity: 60, unitPrice: 9.50, lotNumber: 'LOT-2024-020', expiryDate: nearExpiry },
          { productId: '10', productName: 'Complejo B', quantity: 50, unitPrice: 14.00, lotNumber: 'LOT-2024-VIT02', expiryDate: nearExpiry },
        ],
        subtotal: 1270.00,
        igv: 228.60,
        total: 1498.60,
        notes: 'Compra de protectores gástricos y vitaminas',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 12),
      },
    ],
    subscription: {
      status: 'active',
      plan: 'unlimited_12_months',
      currentPeriodEnd: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
      accessBlocked: false,
    },
    warehouses: [
      {
        id: '1',
        name: 'Almacén Principal',
        location: 'Av. Brasil 1580, Jesús María',
        isDefault: true,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
      {
        id: '2',
        name: 'Mostrador',
        location: 'Av. Brasil 1580, Jesús María',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
    ],
    // Alertas de vencimiento simuladas
    expiryAlerts: [
      {
        id: 'alert1',
        productId: '1',
        productName: 'Paracetamol 500mg',
        lotNumber: 'LOT-2024-002',
        expiryDate: nearExpiry,
        quantity: 50,
        daysUntilExpiry: 30,
        status: 'warning',
      },
      {
        id: 'alert2',
        productId: '4',
        productName: 'Omeprazol 20mg',
        lotNumber: 'LOT-2024-020',
        expiryDate: nearExpiry,
        quantity: 35,
        daysUntilExpiry: 30,
        status: 'warning',
      },
      {
        id: 'alert3',
        productId: '6',
        productName: 'Aspirina 100mg',
        lotNumber: 'LOT-2023-050',
        expiryDate: expired,
        quantity: 10,
        daysUntilExpiry: -30,
        status: 'expired',
      },
      {
        id: 'alert4',
        productId: '10',
        productName: 'Complejo B',
        lotNumber: 'LOT-2024-VIT02',
        expiryDate: nearExpiry,
        quantity: 30,
        daysUntilExpiry: 30,
        status: 'warning',
      },
    ],
    expenses: [
      { id: 'exp1', date: new Date(today.getFullYear(), today.getMonth(), 5), description: 'Pago de luz del local', category: 'servicios', supplier: 'Luz del Sur', reference: 'REC-2024-001', paymentMethod: 'transferencia', amount: 280.00 },
      { id: 'exp2', date: new Date(today.getFullYear(), today.getMonth(), 8), description: 'Internet y teléfono', category: 'servicios', supplier: 'Movistar', reference: 'FAC-123456', paymentMethod: 'transferencia', amount: 150.00 },
      { id: 'exp3', date: new Date(today.getFullYear(), today.getMonth(), 15), description: 'Sueldos del mes', category: 'personal', supplier: '', reference: 'PLANILLA-ENE', paymentMethod: 'transferencia', amount: 5500.00 },
      { id: 'exp4', date: new Date(today.getFullYear(), today.getMonth(), 10), description: 'Alquiler del local', category: 'servicios', supplier: 'Inmobiliaria Central', reference: 'ALQ-ENE-2025', paymentMethod: 'transferencia', amount: 3500.00 },
    ],
    quotations: [
      {
        id: 'cot1',
        number: 'COT-001',
        customer: {
          id: '2',
          documentType: '6',
          documentNumber: '20456789012',
          name: 'CLINICA SAN PABLO SAC',
          email: 'compras@clinicasanpablo.com',
          phone: '987654322',
          address: 'Av. El Polo 789, Surco',
        },
        items: [
          { id: 'item1', productId: '1', code: 'MED001', description: 'Paracetamol 500mg Tabletas', quantity: 50, price: 8.50, unit: 'CAJA', taxAffectation: '10' },
          { id: 'item2', productId: '4', code: 'MED004', description: 'Amoxicilina 500mg Cápsulas', quantity: 30, price: 18.00, unit: 'CAJA', taxAffectation: '10' },
          { id: 'item3', productId: '17', code: 'VIT001', description: 'Vitamina C 1000mg Tabletas', quantity: 20, price: 28.00, unit: 'FRASCO', taxAffectation: '10' },
        ],
        subtotal: 1525.00,
        igv: 274.50,
        total: 1799.50,
        status: 'pending',
        validUntil: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15),
        notes: 'Pedido mensual de medicamentos básicos para la clínica',
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
      },
      {
        id: 'cot2',
        number: 'COT-002',
        customer: {
          id: '4',
          documentType: '6',
          documentNumber: '20567890123',
          name: 'BOTICA POPULAR EIRL',
          email: 'pedidos@boticapopular.com',
          phone: '987654324',
          address: 'Av. Abancay 890, Lima',
        },
        items: [
          { id: 'item4', productId: '2', code: 'MED002', description: 'Ibuprofeno 400mg Tabletas', quantity: 100, price: 12.00, unit: 'CAJA', taxAffectation: '10' },
          { id: 'item5', productId: '10', code: 'MED010', description: 'Omeprazol 20mg Cápsulas', quantity: 80, price: 15.00, unit: 'CAJA', taxAffectation: '10' },
          { id: 'item6', productId: '13', code: 'MED013', description: 'Loratadina 10mg Tabletas', quantity: 50, price: 10.00, unit: 'CAJA', taxAffectation: '10' },
        ],
        subtotal: 2900.00,
        igv: 522.00,
        total: 3422.00,
        status: 'sent',
        isSent: true,
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3),
        validUntil: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7),
        notes: 'Cotización para reposición de stock - solicitan descuento por volumen',
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
      },
      {
        id: 'cot3',
        number: 'COT-003',
        customer: {
          id: '1',
          documentType: '1',
          documentNumber: '45678901',
          name: 'María García López',
          email: 'maria.garcia@email.com',
          phone: '987654321',
          address: 'Av. Salaverry 1234, Jesús María',
        },
        items: [
          { id: 'item7', productId: '18', code: 'VIT002', description: 'Complejo B Tabletas', quantity: 2, price: 22.00, unit: 'FRASCO', taxAffectation: '10' },
          { id: 'item8', productId: '17', code: 'VIT001', description: 'Vitamina C 1000mg Tabletas', quantity: 1, price: 28.00, unit: 'FRASCO', taxAffectation: '10' },
          { id: 'item9', productId: '20', code: 'VIT004', description: 'Hierro + Ácido Fólico Tabletas', quantity: 1, price: 12.00, unit: 'CAJA', taxAffectation: '10' },
        ],
        subtotal: 84.00,
        igv: 15.12,
        total: 99.12,
        status: 'accepted',
        validUntil: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 10),
        notes: 'Vitaminas para tratamiento mensual',
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
      },
      {
        id: 'cot4',
        number: 'COT-004',
        customer: {
          id: '3',
          documentType: '1',
          documentNumber: '32165498',
          name: 'Carlos Mendoza Ríos',
          email: 'carlos.mendoza@email.com',
          phone: '987654323',
          address: 'Jr. Camaná 456, Cercado de Lima',
        },
        items: [
          { id: 'item10', productId: '24', code: 'HIG001', description: 'Alcohol en Gel 500ml', quantity: 5, price: 15.00, unit: 'FRASCO', taxAffectation: '10' },
          { id: 'item11', productId: '30', code: 'MAT001', description: 'Algodón 100g', quantity: 3, price: 6.00, unit: 'BOLSA', taxAffectation: '10' },
          { id: 'item12', productId: '33', code: 'MAT004', description: 'Curitas Adhesivas x100', quantity: 2, price: 12.00, unit: 'CAJA', taxAffectation: '10' },
        ],
        subtotal: 117.00,
        igv: 21.06,
        total: 138.06,
        status: 'expired',
        validUntil: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
        notes: 'Material de primeros auxilios para oficina',
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 20),
      },
    ],
  }
}

export const DemoPharmacyProvider = ({ children }) => {
  const [demoData] = useState(generatePharmacyDemoData())

  // Inyectar datos de demo en window para que los servicios puedan acceder
  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.__DEMO_DATA__ = demoData
    }
    return () => {
      if (typeof window !== 'undefined') {
        delete window.__DEMO_DATA__
      }
    }
  }, [demoData])

  const value = {
    isDemoMode: true,
    demoData,
  }

  return <DemoPharmacyContext.Provider value={value}>{children}</DemoPharmacyContext.Provider>
}

export const useDemoPharmacy = () => {
  const context = useContext(DemoPharmacyContext)
  return context
}

export { DemoPharmacyContext }
