import { createContext, useContext, useState, useEffect } from 'react'

const DemoVeterinaryContext = createContext(null)

// Datos de ejemplo para el demo de veterinaria
const generateVeterinaryDemoData = () => {
  const today = new Date()
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1)
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)

  // Fechas para citas y alertas
  const tomorrow = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1)
  const nextWeek = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7)
  const inTwoWeeks = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 14)

  // Fechas de vencimiento para medicamentos
  const nearExpiry = new Date(today.getFullYear(), today.getMonth() + 1, 15)
  const farExpiry = new Date(today.getFullYear() + 1, today.getMonth(), 1)

  return {
    user: {
      uid: 'demo-veterinary-user',
      email: 'demo@veterinaria.com',
      displayName: 'Usuario Demo Veterinaria',
      photoURL: null,
    },
    business: {
      businessName: 'VETERINARIA HUELLITAS FELICES SAC',
      name: 'VETERINARIA HUELLITAS FELICES SAC',
      ruc: '20567891234',
      address: 'Av. La Marina 2580, San Miguel',
      phone: '01-5678901',
      email: 'contacto@huellitasfelices.com',
      website: 'www.huellitasfelices.com',
      logoUrl: '/demologo.png',
      companySlogan: 'CUIDAMOS A TU MASCOTA COMO PARTE DE NUESTRA FAMILIA',
      mode: 'veterinary',
      businessMode: 'veterinary',
    },
    // Pacientes (mascotas) - cada registro es una mascota con datos del dueño
    customers: [
      {
        id: '1',
        documentType: '1',
        documentNumber: '45678901',
        name: 'María García López',
        email: 'maria.garcia@email.com',
        phone: '987654321',
        address: 'Av. Brasil 1234, Jesús María',
        // Datos de la mascota
        petName: 'Max',
        petSpecies: 'Perro',
        petBreed: 'Golden Retriever',
        petAge: '4 años',
        petWeight: '32',
        petSex: 'Macho',
        petColor: 'Dorado',
        petNotes: 'Alergia al pollo. Microchip: 985141234567890',
      },
      {
        id: '2',
        documentType: '1',
        documentNumber: '32165498',
        name: 'Carlos Mendoza Ríos',
        email: 'carlos.mendoza@email.com',
        phone: '987654322',
        address: 'Jr. Camaná 456, Cercado de Lima',
        petName: 'Luna',
        petSpecies: 'Gato',
        petBreed: 'Persa',
        petAge: '3 años',
        petWeight: '4.5',
        petSex: 'Hembra',
        petColor: 'Blanco',
        petNotes: 'Sobrepeso leve. Esterilizada. Microchip: 985141234567891',
      },
      {
        id: '3',
        documentType: '1',
        documentNumber: '32165498',
        name: 'Carlos Mendoza Ríos',
        email: 'carlos.mendoza@email.com',
        phone: '987654322',
        address: 'Jr. Camaná 456, Cercado de Lima',
        petName: 'Michi',
        petSpecies: 'Gato',
        petBreed: 'Común Europeo',
        petAge: '2 años',
        petWeight: '3.8',
        petSex: 'Macho',
        petColor: 'Atigrado',
        petNotes: 'Pendiente esterilización',
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '71234567',
        name: 'Ana Torres Vega',
        email: 'ana.torres@email.com',
        phone: '987654323',
        address: 'Av. Salaverry 789, San Isidro',
        petName: 'Rocky',
        petSpecies: 'Perro',
        petBreed: 'Bulldog Francés',
        petAge: '5 años',
        petWeight: '12',
        petSex: 'Macho',
        petColor: 'Atigrado',
        petNotes: 'Alergias: Maíz, Soya. Problemas respiratorios. Microchip: 985141234567892',
      },
      {
        id: '5',
        documentType: '1',
        documentNumber: '72345678',
        name: 'Pedro Ruiz Castro',
        email: 'pedro.ruiz@email.com',
        phone: '987654324',
        address: 'Av. Arequipa 1500, Lince',
        petName: 'Coco',
        petSpecies: 'Perro',
        petBreed: 'Poodle',
        petAge: '6 años',
        petWeight: '8',
        petSex: 'Macho',
        petColor: 'Blanco',
        petNotes: 'Diabetes controlada. Esterilizado. Microchip: 985141234567893',
      },
      {
        id: '6',
        documentType: '1',
        documentNumber: '72345678',
        name: 'Pedro Ruiz Castro',
        email: 'pedro.ruiz@email.com',
        phone: '987654324',
        address: 'Av. Arequipa 1500, Lince',
        petName: 'Nieve',
        petSpecies: 'Conejo',
        petBreed: 'Holland Lop',
        petAge: '1 año',
        petWeight: '1.8',
        petSex: 'Hembra',
        petColor: 'Blanco',
        petNotes: 'Mascota exótica - cuidados especiales',
      },
      {
        id: '7',
        documentType: '1',
        documentNumber: '73456789',
        name: 'Rosa Mendez Luna',
        email: 'rosa.mendez@email.com',
        phone: '987654325',
        address: 'Jr. Lampa 890, Centro de Lima',
        petName: 'Toby',
        petSpecies: 'Perro',
        petBreed: 'Labrador',
        petAge: '3 años',
        petWeight: '28',
        petSex: 'Macho',
        petColor: 'Negro',
        petNotes: 'Pendiente vacuna Séxtuple + Rabia. Microchip: 985141234567894',
      },
      {
        id: '8',
        documentType: '1',
        documentNumber: '74567890',
        name: 'Luis Fernández Díaz',
        email: 'luis.fernandez@email.com',
        phone: '987654326',
        address: 'Av. Javier Prado 2500, San Borja',
        petName: 'Pelusa',
        petSpecies: 'Gato',
        petBreed: 'Angora',
        petAge: '2 años',
        petWeight: '3.2',
        petSex: 'Hembra',
        petColor: 'Blanco',
        petNotes: 'Muy asustadiza. Requiere manejo cuidadoso',
      },
      {
        id: '9',
        documentType: '1',
        documentNumber: '75678901',
        name: 'Carmen Soto Pérez',
        email: 'carmen.soto@email.com',
        phone: '987654327',
        address: 'Jr. Ucayali 345, Breña',
        petName: 'Thor',
        petSpecies: 'Perro',
        petBreed: 'Pastor Alemán',
        petAge: '4 años',
        petWeight: '35',
        petSex: 'Macho',
        petColor: 'Negro y Fuego',
        petNotes: 'Perro de trabajo. Muy activo. Microchip: 985141234567895',
      },
      {
        id: '10',
        documentType: '1',
        documentNumber: '76789012',
        name: 'Jorge Quispe Mamani',
        email: 'jorge.quispe@email.com',
        phone: '987654328',
        address: 'Av. Túpac Amaru 1200, Comas',
        petName: 'Copito',
        petSpecies: 'Hamster',
        petBreed: 'Sirio',
        petAge: '8 meses',
        petWeight: '0.12',
        petSex: 'Macho',
        petColor: 'Blanco',
        petNotes: 'Mascota exótica pequeña',
      },
    ],
    // Servicios veterinarios
    services: [
      { id: 'srv1', name: 'Consulta General', price: 50.00, duration: 30, category: 'consulta' },
      { id: 'srv2', name: 'Vacunación', price: 80.00, duration: 20, category: 'vacunacion' },
      { id: 'srv3', name: 'Desparasitación', price: 35.00, duration: 15, category: 'prevencion' },
      { id: 'srv4', name: 'Baño y Corte', price: 60.00, duration: 60, category: 'estetica' },
      { id: 'srv5', name: 'Corte de Uñas', price: 20.00, duration: 15, category: 'estetica' },
      { id: 'srv6', name: 'Limpieza Dental', price: 150.00, duration: 45, category: 'dental' },
      { id: 'srv7', name: 'Cirugía de Esterilización', price: 350.00, duration: 120, category: 'cirugia' },
      { id: 'srv8', name: 'Ecografía', price: 120.00, duration: 30, category: 'diagnostico' },
      { id: 'srv9', name: 'Rayos X', price: 100.00, duration: 30, category: 'diagnostico' },
      { id: 'srv10', name: 'Análisis de Sangre', price: 80.00, duration: 20, category: 'laboratorio' },
      { id: 'srv11', name: 'Hospitalización (por día)', price: 120.00, duration: 1440, category: 'hospitalizacion' },
      { id: 'srv12', name: 'Emergencia', price: 100.00, duration: 60, category: 'emergencia' },
    ],
    // Productos/medicamentos veterinarios
    products: [
      // ========== VACUNAS ==========
      {
        id: '1',
        code: 'VAC001',
        name: 'Vacuna Séxtuple Canina',
        description: 'Protege contra Moquillo, Hepatitis, Parvovirus, Parainfluenza, Leptospira y Coronavirus',
        price: 85.00,
        cost: 45.00,
        stock: 50,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b1', lotNumber: 'LOT-VAC-001', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '2',
        code: 'VAC002',
        name: 'Vacuna Triple Felina',
        description: 'Protege contra Rinotraqueitis, Calicivirus y Panleucopenia',
        price: 75.00,
        cost: 40.00,
        stock: 35,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b2', lotNumber: 'LOT-VAC-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      {
        id: '3',
        code: 'VAC003',
        name: 'Vacuna Antirrábica',
        description: 'Vacuna contra la rabia para perros y gatos',
        price: 45.00,
        cost: 20.00,
        stock: 80,
        unit: 'DOSIS',
        category: 'cat-vacunas',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b3', lotNumber: 'LOT-VAC-003', expiryDate: farExpiry, quantity: 80, isExpired: false },
        ],
      },
      // ========== ANTIPARASITARIOS ==========
      {
        id: '4',
        code: 'PAR001',
        name: 'Desparasitante Interno Canino',
        description: 'Tabletas antiparasitarias de amplio espectro - Caja x 4 tabletas',
        price: 35.00,
        cost: 15.00,
        stock: 60,
        unit: 'CAJA',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b4', lotNumber: 'LOT-PAR-001', expiryDate: farExpiry, quantity: 60, isExpired: false },
        ],
      },
      {
        id: '5',
        code: 'PAR002',
        name: 'Pipeta Antipulgas y Garrapatas',
        description: 'Protección mensual contra pulgas, garrapatas y ácaros - Para perros de 10-25kg',
        price: 55.00,
        cost: 28.00,
        stock: 45,
        unit: 'PIPETA',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b5', lotNumber: 'LOT-PAR-002', expiryDate: nearExpiry, quantity: 45, isExpired: false },
        ],
      },
      {
        id: '6',
        code: 'PAR003',
        name: 'Collar Antipulgas',
        description: 'Collar antiparasitario de larga duración (8 meses) - Talla M/L',
        price: 120.00,
        cost: 65.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'cat-antiparasitarios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b6', lotNumber: 'LOT-PAR-003', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      // ========== ANTIBIÓTICOS ==========
      {
        id: '7',
        code: 'ANT001',
        name: 'Amoxicilina Veterinaria 250mg',
        description: 'Antibiótico de amplio espectro - Caja x 20 tabletas',
        price: 45.00,
        cost: 22.00,
        stock: 40,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
        batches: [
          { id: 'b7', lotNumber: 'LOT-ANT-001', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      {
        id: '8',
        code: 'ANT002',
        name: 'Enrofloxacina 50mg',
        description: 'Antibiótico fluoroquinolona - Caja x 10 tabletas',
        price: 55.00,
        cost: 28.00,
        stock: 30,
        unit: 'CAJA',
        category: 'cat-antibioticos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=400&fit=crop',
        batches: [
          { id: 'b8', lotNumber: 'LOT-ANT-002', expiryDate: nearExpiry, quantity: 30, isExpired: false },
        ],
      },
      // ========== ANTIINFLAMATORIOS ==========
      {
        id: '9',
        code: 'INF001',
        name: 'Meloxicam Veterinario 2mg',
        description: 'Antiinflamatorio no esteroideo - Caja x 10 tabletas',
        price: 38.00,
        cost: 18.00,
        stock: 50,
        unit: 'CAJA',
        category: 'cat-antiinflamatorios',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=400&fit=crop',
        batches: [
          { id: 'b9', lotNumber: 'LOT-INF-001', expiryDate: farExpiry, quantity: 50, isExpired: false },
        ],
      },
      {
        id: '10',
        code: 'INF002',
        name: 'Prednisolona 5mg',
        description: 'Corticosteroide - Caja x 20 tabletas',
        price: 42.00,
        cost: 20.00,
        stock: 35,
        unit: 'CAJA',
        category: 'cat-antiinflamatorios',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=400&fit=crop',
        batches: [
          { id: 'b10', lotNumber: 'LOT-INF-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      // ========== ALIMENTOS ==========
      {
        id: '11',
        code: 'ALI001',
        name: 'Alimento Premium Perro Adulto 15kg',
        description: 'Alimento balanceado premium para perros adultos',
        price: 180.00,
        cost: 110.00,
        stock: 20,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b11', lotNumber: 'LOT-ALI-001', expiryDate: farExpiry, quantity: 20, isExpired: false },
        ],
      },
      {
        id: '12',
        code: 'ALI002',
        name: 'Alimento Premium Gato Adulto 8kg',
        description: 'Alimento balanceado premium para gatos adultos',
        price: 150.00,
        cost: 95.00,
        stock: 18,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b12', lotNumber: 'LOT-ALI-002', expiryDate: farExpiry, quantity: 18, isExpired: false },
        ],
      },
      {
        id: '13',
        code: 'ALI003',
        name: 'Alimento Medicado Renal Canino 3kg',
        description: 'Dieta especial para perros con problemas renales',
        price: 120.00,
        cost: 75.00,
        stock: 12,
        unit: 'BOLSA',
        category: 'cat-alimentos',
        requiresPrescription: true,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b13', lotNumber: 'LOT-ALI-003', expiryDate: farExpiry, quantity: 12, isExpired: false },
        ],
      },
      // ========== ACCESORIOS ==========
      {
        id: '14',
        code: 'ACC001',
        name: 'Collar Ajustable Perro M',
        description: 'Collar de nylon ajustable para perros medianos',
        price: 25.00,
        cost: 12.00,
        stock: 30,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '15',
        code: 'ACC002',
        name: 'Correa Retráctil 5m',
        description: 'Correa retráctil para paseos',
        price: 45.00,
        cost: 22.00,
        stock: 20,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '16',
        code: 'ACC003',
        name: 'Cama para Mascota M',
        description: 'Cama acolchada lavable talla M',
        price: 85.00,
        cost: 45.00,
        stock: 15,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '23',
        code: 'ACC004',
        name: 'Cama para Mascota L',
        description: 'Cama acolchada lavable talla L para perros grandes',
        price: 120.00,
        cost: 65.00,
        stock: 10,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '24',
        code: 'ACC005',
        name: 'Plato Doble Acero Inoxidable',
        description: 'Comedero y bebedero doble de acero inoxidable',
        price: 35.00,
        cost: 18.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '25',
        code: 'ACC006',
        name: 'Transportadora Perro M',
        description: 'Kennel de transporte para perros medianos',
        price: 150.00,
        cost: 85.00,
        stock: 8,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '26',
        code: 'ACC007',
        name: 'Transportadora Gato',
        description: 'Kennel de transporte para gatos',
        price: 95.00,
        cost: 50.00,
        stock: 12,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '27',
        code: 'ACC008',
        name: 'Arnés Ajustable M',
        description: 'Arnés de paseo ajustable talla M',
        price: 45.00,
        cost: 22.00,
        stock: 20,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '28',
        code: 'ACC009',
        name: 'Rascador para Gatos',
        description: 'Rascador de sisal con plataforma',
        price: 75.00,
        cost: 40.00,
        stock: 10,
        unit: 'UNIDAD',
        category: 'cat-accesorios',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=400&fit=crop',
        batches: [],
      },
      // ========== JUGUETES ==========
      {
        id: '29',
        code: 'JUG001',
        name: 'Pelota de Goma Resistente',
        description: 'Pelota de goma para perros - resistente a mordidas',
        price: 18.00,
        cost: 8.00,
        stock: 40,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '30',
        code: 'JUG002',
        name: 'Hueso de Nylon',
        description: 'Hueso masticable de nylon - limpia dientes',
        price: 22.00,
        cost: 10.00,
        stock: 35,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '31',
        code: 'JUG003',
        name: 'Cuerda de Algodón',
        description: 'Juguete de cuerda trenzada para tirar',
        price: 15.00,
        cost: 6.00,
        stock: 30,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '32',
        code: 'JUG004',
        name: 'Ratón de Peluche para Gato',
        description: 'Ratón de peluche con cascabel',
        price: 12.00,
        cost: 5.00,
        stock: 45,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '33',
        code: 'JUG005',
        name: 'Caña con Plumas para Gato',
        description: 'Juguete interactivo con plumas',
        price: 20.00,
        cost: 9.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      {
        id: '34',
        code: 'JUG006',
        name: 'Kong Classic M',
        description: 'Juguete rellenable de goma - talla M',
        price: 55.00,
        cost: 28.00,
        stock: 15,
        unit: 'UNIDAD',
        category: 'cat-juguetes',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=400&h=400&fit=crop',
        batches: [],
      },
      // ========== SNACKS Y PREMIOS ==========
      {
        id: '35',
        code: 'SNK001',
        name: 'Galletas para Perro x 500g',
        description: 'Galletas de entrenamiento sabor pollo',
        price: 25.00,
        cost: 12.00,
        stock: 30,
        unit: 'BOLSA',
        category: 'cat-snacks',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&h=400&fit=crop',
        batches: [
          { id: 'b35', lotNumber: 'LOT-SNK-001', expiryDate: farExpiry, quantity: 30, isExpired: false },
        ],
      },
      {
        id: '36',
        code: 'SNK002',
        name: 'Snacks Dentales x 7 unid',
        description: 'Palitos dentales para limpieza bucal',
        price: 28.00,
        cost: 14.00,
        stock: 25,
        unit: 'PAQUETE',
        category: 'cat-snacks',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&h=400&fit=crop',
        batches: [
          { id: 'b36', lotNumber: 'LOT-SNK-002', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      {
        id: '37',
        code: 'SNK003',
        name: 'Premios para Gato x 100g',
        description: 'Snacks crocantes sabor salmón',
        price: 18.00,
        cost: 8.00,
        stock: 35,
        unit: 'BOLSA',
        category: 'cat-snacks',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&h=400&fit=crop',
        batches: [
          { id: 'b37', lotNumber: 'LOT-SNK-003', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      {
        id: '38',
        code: 'SNK004',
        name: 'Carnaza Natural x 3 unid',
        description: 'Huesos de carnaza natural para perros',
        price: 22.00,
        cost: 10.00,
        stock: 20,
        unit: 'PAQUETE',
        category: 'cat-snacks',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=400&h=400&fit=crop',
        batches: [
          { id: 'b38', lotNumber: 'LOT-SNK-004', expiryDate: farExpiry, quantity: 20, isExpired: false },
        ],
      },
      // ========== MÁS ALIMENTOS ==========
      {
        id: '39',
        code: 'ALI004',
        name: 'Alimento Cachorro 8kg',
        description: 'Alimento premium para cachorros hasta 12 meses',
        price: 165.00,
        cost: 100.00,
        stock: 15,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b39', lotNumber: 'LOT-ALI-004', expiryDate: farExpiry, quantity: 15, isExpired: false },
        ],
      },
      {
        id: '40',
        code: 'ALI005',
        name: 'Alimento Perro Senior 8kg',
        description: 'Alimento para perros mayores de 7 años',
        price: 170.00,
        cost: 105.00,
        stock: 12,
        unit: 'SACO',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b40', lotNumber: 'LOT-ALI-005', expiryDate: farExpiry, quantity: 12, isExpired: false },
        ],
      },
      {
        id: '41',
        code: 'ALI006',
        name: 'Alimento Húmedo Perro x 6 latas',
        description: 'Comida húmeda premium - pack 6 latas 400g',
        price: 65.00,
        cost: 38.00,
        stock: 20,
        unit: 'PACK',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b41', lotNumber: 'LOT-ALI-006', expiryDate: farExpiry, quantity: 20, isExpired: false },
        ],
      },
      {
        id: '42',
        code: 'ALI007',
        name: 'Alimento Húmedo Gato x 12 sobres',
        description: 'Comida húmeda para gatos - pack 12 sobres 85g',
        price: 48.00,
        cost: 28.00,
        stock: 25,
        unit: 'PACK',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [
          { id: 'b42', lotNumber: 'LOT-ALI-007', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      {
        id: '43',
        code: 'ALI008',
        name: 'Arena para Gato 10kg',
        description: 'Arena aglomerante sin fragancia',
        price: 45.00,
        cost: 25.00,
        stock: 30,
        unit: 'BOLSA',
        category: 'cat-alimentos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=400&h=400&fit=crop',
        batches: [],
      },
      // ========== HIGIENE ==========
      {
        id: '17',
        code: 'HIG001',
        name: 'Shampoo Antipulgas 500ml',
        description: 'Shampoo medicado antipulgas y garrapatas',
        price: 35.00,
        cost: 18.00,
        stock: 40,
        unit: 'FRASCO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b17', lotNumber: 'LOT-HIG-001', expiryDate: farExpiry, quantity: 40, isExpired: false },
        ],
      },
      {
        id: '18',
        code: 'HIG002',
        name: 'Limpiador de Oídos 120ml',
        description: 'Solución limpiadora ótica para perros y gatos',
        price: 28.00,
        cost: 14.00,
        stock: 35,
        unit: 'FRASCO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b18', lotNumber: 'LOT-HIG-002', expiryDate: farExpiry, quantity: 35, isExpired: false },
        ],
      },
      {
        id: '19',
        code: 'HIG003',
        name: 'Pasta Dental Veterinaria',
        description: 'Pasta dental sabor pollo para perros y gatos',
        price: 22.00,
        cost: 10.00,
        stock: 25,
        unit: 'TUBO',
        category: 'cat-higiene',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1584483720412-ce931f4aefa8?w=400&h=400&fit=crop',
        batches: [
          { id: 'b19', lotNumber: 'LOT-HIG-003', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      // ========== SUPLEMENTOS ==========
      {
        id: '20',
        code: 'SUP001',
        name: 'Omega 3-6-9 para Mascotas',
        description: 'Suplemento para piel y pelo - Frasco x 60 cápsulas',
        price: 65.00,
        cost: 35.00,
        stock: 30,
        unit: 'FRASCO',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b20', lotNumber: 'LOT-SUP-001', expiryDate: farExpiry, quantity: 30, isExpired: false },
        ],
      },
      {
        id: '21',
        code: 'SUP002',
        name: 'Glucosamina + Condroitina',
        description: 'Suplemento para articulaciones - Frasco x 60 tabletas',
        price: 85.00,
        cost: 45.00,
        stock: 25,
        unit: 'FRASCO',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b21', lotNumber: 'LOT-SUP-002', expiryDate: farExpiry, quantity: 25, isExpired: false },
        ],
      },
      {
        id: '22',
        code: 'SUP003',
        name: 'Probióticos Veterinarios',
        description: 'Suplemento digestivo - Caja x 30 sobres',
        price: 55.00,
        cost: 28.00,
        stock: 35,
        unit: 'CAJA',
        category: 'cat-suplementos',
        requiresPrescription: false,
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1577401239170-897942555fb3?w=400&h=400&fit=crop',
        batches: [
          { id: 'b22', lotNumber: 'LOT-SUP-003', expiryDate: nearExpiry, quantity: 35, isExpired: false },
        ],
      },
    ],
    categories: [
      { id: 'cat-vacunas', name: 'Vacunas', parentId: null },
      { id: 'cat-antiparasitarios', name: 'Antiparasitarios', parentId: null },
      { id: 'cat-antibioticos', name: 'Antibióticos', parentId: null },
      { id: 'cat-antiinflamatorios', name: 'Antiinflamatorios', parentId: null },
      { id: 'cat-alimentos', name: 'Alimentos', parentId: null },
      { id: 'cat-accesorios', name: 'Accesorios', parentId: null },
      { id: 'cat-juguetes', name: 'Juguetes', parentId: null },
      { id: 'cat-snacks', name: 'Snacks y Premios', parentId: null },
      { id: 'cat-higiene', name: 'Higiene', parentId: null },
      { id: 'cat-suplementos', name: 'Suplementos', parentId: null },
    ],
    // Citas/Agenda
    appointments: [
      {
        id: 'apt1',
        petId: 'pet3',
        petName: 'Michi',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: tomorrow,
        time: '09:00',
        duration: 20,
        status: 'confirmed',
        notes: 'Vacuna Triple Felina - Primera dosis',
        veterinarian: 'Dr. Juan Pérez',
      },
      {
        id: 'apt2',
        petId: 'pet1',
        petName: 'Max',
        ownerName: 'María García López',
        ownerPhone: '987654321',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: nextWeek,
        time: '10:30',
        duration: 20,
        status: 'pending',
        notes: 'Refuerzo Séxtuple',
        veterinarian: 'Dra. Ana Rodríguez',
      },
      {
        id: 'apt3',
        petId: 'pet5',
        petName: 'Coco',
        ownerName: 'Pedro Ruiz Castro',
        ownerPhone: '987654324',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: nextWeek,
        time: '11:00',
        duration: 20,
        status: 'pending',
        notes: 'Vacuna antirrábica anual',
        veterinarian: 'Dr. Juan Pérez',
      },
      {
        id: 'apt4',
        petId: 'pet4',
        petName: 'Rocky',
        ownerName: 'Ana Torres Vega',
        ownerPhone: '987654323',
        service: 'Consulta General',
        serviceId: 'srv1',
        date: tomorrow,
        time: '15:00',
        duration: 30,
        status: 'confirmed',
        notes: 'Control de problemas respiratorios',
        veterinarian: 'Dra. Ana Rodríguez',
      },
      {
        id: 'apt5',
        petId: 'pet7',
        petName: 'Toby',
        ownerName: 'Rosa Mendez Luna',
        ownerPhone: '987654325',
        service: 'Baño y Corte',
        serviceId: 'srv4',
        date: inTwoWeeks,
        time: '09:00',
        duration: 60,
        status: 'pending',
        notes: 'Baño completo y corte de pelo',
        veterinarian: null,
      },
      {
        id: 'apt6',
        petId: 'pet2',
        petName: 'Luna',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        service: 'Vacunación',
        serviceId: 'srv2',
        date: inTwoWeeks,
        time: '10:00',
        duration: 20,
        status: 'pending',
        notes: 'Triple Felina - Refuerzo anual',
        veterinarian: 'Dr. Juan Pérez',
      },
    ],
    // Alertas de vacunación
    vaccineAlerts: [
      {
        id: 'valert1',
        petId: 'pet3',
        petName: 'Michi',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        vaccineType: 'Triple Felina',
        dueDate: tomorrow,
        status: 'urgent',
        daysUntilDue: 1,
      },
      {
        id: 'valert2',
        petId: 'pet1',
        petName: 'Max',
        ownerName: 'María García López',
        ownerPhone: '987654321',
        vaccineType: 'Refuerzo Séxtuple',
        dueDate: nextWeek,
        status: 'upcoming',
        daysUntilDue: 7,
      },
      {
        id: 'valert3',
        petId: 'pet5',
        petName: 'Coco',
        ownerName: 'Pedro Ruiz Castro',
        ownerPhone: '987654324',
        vaccineType: 'Rabia',
        dueDate: nextWeek,
        status: 'upcoming',
        daysUntilDue: 7,
      },
      {
        id: 'valert4',
        petId: 'pet2',
        petName: 'Luna',
        ownerName: 'Carlos Mendoza Ríos',
        ownerPhone: '987654322',
        vaccineType: 'Triple Felina',
        dueDate: inTwoWeeks,
        status: 'scheduled',
        daysUntilDue: 14,
      },
      {
        id: 'valert5',
        petId: 'pet7',
        petName: 'Toby',
        ownerName: 'Rosa Mendez Luna',
        ownerPhone: '987654325',
        vaccineType: 'Séxtuple + Rabia',
        dueDate: inTwoWeeks,
        status: 'scheduled',
        daysUntilDue: 14,
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '45678901', name: 'María García López', phone: '987654321' },
        items: [
          { code: 'SRV', description: 'Consulta General - Max', quantity: 1, price: 50.00 },
          { code: 'VAC001', description: 'Vacuna Séxtuple Canina', quantity: 1, price: 85.00 },
        ],
        subtotal: 135.00,
        tax: 24.30,
        total: 159.30,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 1),
      },
      {
        id: '2',
        number: 'B001-00000002',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '32165498', name: 'Carlos Mendoza Ríos', phone: '987654322' },
        items: [
          { code: 'SRV', description: 'Consulta General - Luna', quantity: 1, price: 50.00 },
          { code: 'PAR001', description: 'Desparasitante Interno', quantity: 1, price: 35.00 },
          { code: 'ALI002', description: 'Alimento Premium Gato 8kg', quantity: 1, price: 150.00 },
        ],
        subtotal: 235.00,
        tax: 42.30,
        total: 277.30,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 3),
      },
      {
        id: '3',
        number: 'B001-00000003',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '71234567', name: 'Ana Torres Vega', phone: '987654323' },
        items: [
          { code: 'SRV', description: 'Consulta General - Rocky', quantity: 1, price: 50.00 },
          { code: 'SRV', description: 'Rayos X', quantity: 1, price: 100.00 },
          { code: 'INF001', description: 'Meloxicam Veterinario', quantity: 1, price: 38.00 },
        ],
        subtotal: 188.00,
        tax: 33.84,
        total: 221.84,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '4',
        number: 'B001-00000004',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '72345678', name: 'Pedro Ruiz Castro', phone: '987654324' },
        items: [
          { code: 'SRV', description: 'Consulta General - Coco', quantity: 1, price: 50.00 },
          { code: 'SRV', description: 'Análisis de Sangre', quantity: 1, price: 80.00 },
          { code: 'ALI003', description: 'Alimento Medicado Renal', quantity: 1, price: 120.00 },
        ],
        subtotal: 250.00,
        tax: 45.00,
        total: 295.00,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 8),
      },
      {
        id: '5',
        number: 'B001-00000005',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '73456789', name: 'Rosa Mendez Luna', phone: '987654325' },
        items: [
          { code: 'SRV', description: 'Baño y Corte - Toby', quantity: 1, price: 60.00 },
          { code: 'HIG001', description: 'Shampoo Antipulgas', quantity: 1, price: 35.00 },
          { code: 'ACC001', description: 'Collar Ajustable M', quantity: 1, price: 25.00 },
        ],
        subtotal: 120.00,
        tax: 21.60,
        total: 141.60,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 10),
      },
      // Ventas del mes pasado
      {
        id: '6',
        number: 'B001-00000006',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '45678901', name: 'María García López', phone: '987654321' },
        items: [
          { code: 'PAR002', description: 'Pipeta Antipulgas', quantity: 2, price: 55.00 },
          { code: 'ALI001', description: 'Alimento Premium Perro 15kg', quantity: 1, price: 180.00 },
        ],
        subtotal: 290.00,
        tax: 52.20,
        total: 342.20,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 15),
      },
      {
        id: '7',
        number: 'B001-00000007',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '71234567', name: 'Ana Torres Vega', phone: '987654323' },
        items: [
          { code: 'SRV', description: 'Cirugía de Esterilización - Rocky', quantity: 1, price: 350.00 },
          { code: 'ANT001', description: 'Amoxicilina Veterinaria', quantity: 1, price: 45.00 },
          { code: 'INF001', description: 'Meloxicam Veterinario', quantity: 1, price: 38.00 },
        ],
        subtotal: 433.00,
        tax: 77.94,
        total: 510.94,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
      },
    ],
    suppliers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20123456789',
        businessName: 'DISTRIBUIDORA VETERINARIA DEL PERÚ SAC',
        contactName: 'Juan Rodríguez',
        email: 'ventas@distveterinaria.com',
        phone: '987111222',
        address: 'Av. Colonial 4567, Callao',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20234567890',
        businessName: 'LABORATORIOS VET PHARMA SAC',
        contactName: 'María González',
        email: 'compras@vetpharma.com',
        phone: '987222333',
        address: 'Av. Argentina 2020, Lima',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20345678901',
        businessName: 'ALIMENTOS MASCOTAS PERÚ EIRL',
        contactName: 'Carlos Pérez',
        email: 'ventas@alimentosmascotas.com',
        phone: '987333444',
        address: 'Av. Santa Rosa 390, Ate',
      },
    ],
    subscription: {
      status: 'active',
      plan: 'unlimited_12_months',
      currentPeriodEnd: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
      accessBlocked: false,
    },
    warehouses: [
      {
        id: '1',
        name: 'Almacén Principal',
        location: 'Av. La Marina 2580, San Miguel',
        isDefault: true,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
      {
        id: '2',
        name: 'Mostrador',
        location: 'Av. La Marina 2580, San Miguel',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 6, 1),
      },
    ],
    expenses: [
      { id: 'exp1', date: new Date(today.getFullYear(), today.getMonth(), 5), description: 'Pago de luz del local', category: 'servicios', supplier: 'Luz del Sur', reference: 'REC-2024-001', paymentMethod: 'transferencia', amount: 320.00 },
      { id: 'exp2', date: new Date(today.getFullYear(), today.getMonth(), 8), description: 'Internet y teléfono', category: 'servicios', supplier: 'Movistar', reference: 'FAC-123456', paymentMethod: 'transferencia', amount: 180.00 },
      { id: 'exp3', date: new Date(today.getFullYear(), today.getMonth(), 15), description: 'Sueldos del mes', category: 'personal', supplier: '', reference: 'PLANILLA-ENE', paymentMethod: 'transferencia', amount: 8500.00 },
      { id: 'exp4', date: new Date(today.getFullYear(), today.getMonth(), 10), description: 'Alquiler del local', category: 'servicios', supplier: 'Inmobiliaria Central', reference: 'ALQ-ENE-2025', paymentMethod: 'transferencia', amount: 4500.00 },
    ],
    // Pedidos online de la tienda (alimentos y accesorios a domicilio).
    onlineOrders: [
      {
        id: 'vord1', orderNumber: 3061, source: 'menu_digital', status: 'pending',
        createdAt: new Date(today.getTime() - 10 * 60000),
        customerName: 'María García', customerPhone: '51987101010', customerEmail: 'maria.garcia@gmail.com',
        customerAddress: 'Av. Primavera 980, Surco',
        notes: 'Tocar el timbre del 3er piso.',
        items: [
          { productId: '41', name: 'Alimento Húmedo Perro x 6 latas', price: 65.00, quantity: 1, total: 65.00 },
          { productId: '35', name: 'Galletas para Perro x 500g', price: 25.00, quantity: 1, total: 25.00 },
        ],
        subtotal: 90.00, total: 90.00,
      },
      {
        id: 'vord2', orderNumber: 3060, source: 'menu_digital', status: 'pending',
        createdAt: new Date(today.getTime() - 50 * 60000),
        customerName: 'Carlos Mendoza', customerPhone: '51986202020', customerEmail: '',
        customerAddress: 'Calle Tarata 240, Miraflores',
        notes: '',
        items: [
          { productId: '43', name: 'Arena para Gato 10kg', price: 45.00, quantity: 1, total: 45.00 },
          { productId: '42', name: 'Alimento Húmedo Gato x 12 sobres', price: 48.00, quantity: 1, total: 48.00 },
        ],
        subtotal: 93.00, total: 93.00,
      },
      {
        id: 'vord3', orderNumber: 3059, source: 'menu_digital', status: 'accepted',
        createdAt: new Date(today.getTime() - 200 * 60000),
        customerName: 'Ana Torres', customerPhone: '51988303030', customerEmail: 'ana.torres@gmail.com',
        customerAddress: 'Av. La Molina 1500, La Molina',
        notes: 'Perro grande, traer bolsa de 8kg.',
        items: [
          { productId: '39', name: 'Alimento Cachorro 8kg', price: 165.00, quantity: 1, total: 165.00 },
          { productId: '36', name: 'Snacks Dentales x 7 unid', price: 28.00, quantity: 2, total: 56.00 },
        ],
        subtotal: 221.00, total: 221.00,
      },
      {
        id: 'vord4', orderNumber: 3058, source: 'menu_digital', status: 'ready',
        createdAt: new Date(today.getTime() - 320 * 60000),
        customerName: 'Pedro Ruiz', customerPhone: '51977404040', customerEmail: '',
        customerAddress: 'Jr. Áncash 410, Cercado de Lima',
        notes: 'Recoge en local.',
        items: [
          { productId: '17', name: 'Shampoo Antipulgas 500ml', price: 35.00, quantity: 1, total: 35.00 },
          { productId: '28', name: 'Rascador para Gatos', price: 75.00, quantity: 1, total: 75.00 },
        ],
        subtotal: 110.00, total: 110.00,
      },
      {
        id: 'vord5', orderNumber: 3057, source: 'menu_digital', status: 'completed',
        createdAt: new Date(today.getTime() - 1 * 24 * 60 * 60000),
        customerName: 'María García', customerPhone: '51987101010', customerEmail: 'maria.garcia@gmail.com',
        customerAddress: 'Av. Primavera 980, Surco',
        notes: '',
        items: [
          { productId: '35', name: 'Galletas para Perro x 500g', price: 25.00, quantity: 2, total: 50.00 },
        ],
        subtotal: 50.00, total: 50.00,
      },
      {
        id: 'vord6', orderNumber: 3056, source: 'menu_digital', status: 'completed',
        createdAt: new Date(today.getTime() - 4 * 24 * 60 * 60000),
        customerName: 'Rosa Méndez', customerPhone: '51966505050', customerEmail: 'rosa.mendez@gmail.com',
        customerAddress: 'Av. Universitaria 2200, San Miguel',
        notes: '',
        items: [
          { productId: '42', name: 'Alimento Húmedo Gato x 12 sobres', price: 48.00, quantity: 1, total: 48.00 },
          { productId: '43', name: 'Arena para Gato 10kg', price: 45.00, quantity: 1, total: 45.00 },
        ],
        subtotal: 93.00, total: 93.00,
      },
      {
        id: 'vord7', orderNumber: 3055, source: 'menu_digital', status: 'cancelled',
        createdAt: new Date(today.getTime() - 3 * 24 * 60 * 60000),
        customerName: 'Luis Fernández', customerPhone: '51955606060', customerEmail: '',
        customerAddress: 'Calle Berlín 120, Miraflores',
        notes: 'Cliente canceló: encontró stock más cerca.',
        items: [
          { productId: '41', name: 'Alimento Húmedo Perro x 6 latas', price: 65.00, quantity: 1, total: 65.00 },
        ],
        subtotal: 65.00, total: 65.00,
      },
    ],
    // Personal y asistencia
    employees: [
      { id: 'vemp1', uid: 'vemp1', displayName: 'Dr. Andrés Palomino', email: 'andres@veterinariademo.com', department: 'Clínica', jobTitle: 'Médico Veterinario', hrStatus: 'active', employmentType: 'full_time' },
      { id: 'vemp2', uid: 'vemp2', displayName: 'Karina Flores', email: 'karina@veterinariademo.com', department: 'Tienda', jobTitle: 'Asistente de Tienda', hrStatus: 'active', employmentType: 'full_time' },
      { id: 'vemp3', uid: 'vemp3', displayName: 'Luis Condori', email: 'luis@veterinariademo.com', department: 'Clínica', jobTitle: 'Auxiliar Veterinario', hrStatus: 'active', employmentType: 'part_time' },
    ],
    attendanceRecords: [
      { id: 'vatt1', userId: 'vemp1', userName: 'Dr. Andrés Palomino', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 0), approvalStatus: 'approved', notes: '' },
      { id: 'vatt2', userId: 'vemp2', userName: 'Karina Flores', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 5), approvalStatus: 'approved', notes: '' },
      { id: 'vatt3', userId: 'vemp3', userName: 'Luis Condori', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 20), approvalStatus: 'pending', notes: '' },
      { id: 'vatt4', userId: 'vemp1', userName: 'Dr. Andrés Palomino', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 9, 0), approvalStatus: 'approved', notes: '' },
      { id: 'vatt5', userId: 'vemp1', userName: 'Dr. Andrés Palomino', branchId: 'main', branchName: 'Veterinaria Demo', type: 'out', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 19, 0), approvalStatus: 'approved', notes: '' },
      { id: 'vatt6', userId: 'vemp2', userName: 'Karina Flores', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 9, 3), approvalStatus: 'approved', notes: '' },
      { id: 'vatt7', userId: 'vemp2', userName: 'Karina Flores', branchId: 'main', branchName: 'Veterinaria Demo', type: 'out', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1, 18, 55), approvalStatus: 'approved', notes: '' },
      { id: 'vatt8', userId: 'vemp3', userName: 'Luis Condori', branchId: 'main', branchName: 'Veterinaria Demo', type: 'in', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2, 9, 15), approvalStatus: 'approved', notes: '' },
      { id: 'vatt9', userId: 'vemp3', userName: 'Luis Condori', branchId: 'main', branchName: 'Veterinaria Demo', type: 'out', timestamp: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2, 14, 0), approvalStatus: 'approved', notes: '' },
    ],
  }
}

export const DemoVeterinaryProvider = ({ children }) => {
  const [demoData] = useState(generateVeterinaryDemoData())

  // Inyectar datos de demo en window para que los servicios puedan acceder
  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.__DEMO_DATA__ = demoData
    }
    return () => {
      if (typeof window !== 'undefined') {
        delete window.__DEMO_DATA__
      }
    }
  }, [demoData])

  const value = {
    isDemoMode: true,
    demoData,
  }

  return <DemoVeterinaryContext.Provider value={value}>{children}</DemoVeterinaryContext.Provider>
}

export const useDemoVeterinary = () => {
  const context = useContext(DemoVeterinaryContext)
  return context
}

export { DemoVeterinaryContext }
