import { createContext, useContext, useState, useEffect } from 'react'

const DemoContext = createContext(null)

// Datos de ejemplo para el demo
const generateDemoData = () => {
  const today = new Date()
  const thisMonth = new Date(today.getFullYear(), today.getMonth(), 1)
  const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1)

  return {
    user: {
      uid: 'demo-user',
      email: 'demo@facturacion.pe',
      displayName: 'Usuario Demo',
      photoURL: null,
    },
    business: {
      businessName: 'EMPRESA DEMO SAC',
      name: 'EMPRESA DEMO SAC',
      ruc: '20123456789',
      address: 'Av. Larco 1234, Miraflores',
      phone: '01-2345678',
      email: 'ventas@empresademo.com',
      website: 'www.empresademo.com',
      logoUrl: '/demologo.png',
      companySlogan: 'SOLUCIONES TECNOLÓGICAS PARA TU NEGOCIO - VENTA DE EQUIPOS, SOPORTE TÉCNICO Y ASESORÍA EMPRESARIAL',
      // Configuración del catálogo
      catalogEnabled: true,
      catalogSlug: 'demo',
      catalogTagline: 'Tu tienda de tecnología y belleza',
      catalogWelcome: 'Bienvenido a nuestra tienda. Explora nuestros productos de electrónica y belleza.',
      catalogColor: '#10B981',
      catalogWhatsapp: '51987654321',
      catalogShowPrices: true,
      catalogAllowOrders: true,
    },
    products: [
      // Productos de electrónica
      {
        id: '1',
        code: 'PROD001',
        name: 'Laptop HP 15"',
        description: 'Laptop HP 15 pulgadas, Intel Core i5, 8GB RAM',
        price: 2500.00,
        cost: 1800.00,
        stock: 15,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 10 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 5 },
        ],
      },
      {
        id: '2',
        code: 'PROD002',
        name: 'Mouse Inalámbrico',
        description: 'Mouse inalámbrico Logitech',
        price: 45.00,
        cost: 25.00,
        stock: 50,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 30 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 20 },
        ],
      },
      {
        id: '3',
        code: 'PROD003',
        name: 'Teclado Mecánico',
        description: 'Teclado mecánico RGB',
        price: 180.00,
        cost: 120.00,
        stock: 25,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 15 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 10 },
        ],
      },
      {
        id: '4',
        code: 'PROD004',
        name: 'Monitor 24"',
        description: 'Monitor LED 24 pulgadas Full HD',
        price: 650.00,
        cost: 450.00,
        stock: 12,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 8 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 4 },
        ],
      },
      // Productos de spa/belleza
      {
        id: '5',
        code: 'PROD005',
        name: 'Crema Hidratante Facial',
        description: 'Crema hidratante profesional para tratamientos faciales',
        price: 85.00,
        cost: 45.00,
        stock: 24,
        unit: 'UNIDAD',
        category: 'cat-belleza',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 24 },
        ],
      },
      {
        id: '6',
        code: 'PROD006',
        name: 'Aceite Esencial Lavanda',
        description: 'Aceite esencial puro para aromaterapia',
        price: 65.00,
        cost: 28.00,
        stock: 18,
        unit: 'UNIDAD',
        category: 'cat-belleza',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 18 },
        ],
      },
      // Más productos de electrónica
      {
        id: '7',
        code: 'PROD007',
        name: 'Audífonos Bluetooth',
        description: 'Audífonos inalámbricos con cancelación de ruido',
        price: 250.00,
        cost: 150.00,
        stock: 35,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 25 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 10 },
        ],
      },
      {
        id: '8',
        code: 'PROD008',
        name: 'Webcam HD 1080p',
        description: 'Cámara web Full HD con micrófono integrado',
        price: 180.00,
        cost: 95.00,
        stock: 28,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1587826080692-f439cd0b70da?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 20 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 8 },
        ],
      },
      {
        id: '9',
        code: 'PROD009',
        name: 'Hub USB 7 puertos',
        description: 'Hub USB 3.0 de 7 puertos con alimentación',
        price: 85.00,
        cost: 45.00,
        stock: 42,
        unit: 'UNIDAD',
        category: 'cat-electronica',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1625723044792-44de16ccb4e9?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '1', warehouseName: 'Almacén Principal', stock: 30 },
          { warehouseId: '2', warehouseName: 'Almacén Secundario', stock: 12 },
        ],
      },
      // Más productos de belleza
      {
        id: '10',
        code: 'PROD010',
        name: 'Mascarilla Facial',
        description: 'Mascarilla hidratante de colágeno',
        price: 35.00,
        cost: 12.00,
        stock: 60,
        unit: 'UNIDAD',
        category: 'cat-belleza',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 60 },
        ],
      },
      {
        id: '11',
        code: 'PROD011',
        name: 'Sérum Vitamina C',
        description: 'Sérum antioxidante con vitamina C pura',
        price: 95.00,
        cost: 38.00,
        stock: 32,
        unit: 'UNIDAD',
        category: 'cat-belleza',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 32 },
        ],
      },
      {
        id: '12',
        code: 'PROD012',
        name: 'Kit Manicure Profesional',
        description: 'Set completo de herramientas para manicure',
        price: 120.00,
        cost: 55.00,
        stock: 20,
        unit: 'UNIDAD',
        category: 'cat-belleza',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400&h=400&fit=crop',
        warehouseStocks: [
          { warehouseId: '3', warehouseName: 'Almacén de Belleza', stock: 20 },
        ],
      },
      // Servicios
      {
        id: 'srv1',
        code: 'SERV001',
        name: 'Servicio de Instalación',
        description: 'Instalación de software y configuración',
        price: 120.00,
        cost: 0,
        stock: null,
        unit: 'SERVICIO',
        category: 'cat-servicios-tecnicos',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=400&h=400&fit=crop',
      },
      {
        id: 'srv2',
        code: 'SERV002',
        name: 'Limpieza Facial Profunda',
        description: 'Tratamiento completo de limpieza facial con productos premium',
        price: 120.00,
        cost: 35.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'cat-servicios-spa',
        hasVariants: false,
        hasRecipe: true,
        imageUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&h=400&fit=crop',
      },
      {
        id: 'srv3',
        code: 'SERV003',
        name: 'Masaje Relajante con Aromaterapia',
        description: 'Masaje de 60 minutos con aceites esenciales',
        price: 180.00,
        cost: 25.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'cat-servicios-spa',
        hasVariants: false,
        hasRecipe: true,
        imageUrl: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=400&fit=crop',
      },
      {
        id: 'srv4',
        code: 'SERV004',
        name: 'Mantenimiento de Equipos',
        description: 'Servicio de mantenimiento preventivo de computadoras',
        price: 150.00,
        cost: 30.00,
        stock: null,
        unit: 'SERVICIO',
        category: 'cat-servicios-tecnicos',
        hasVariants: false,
        imageUrl: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=400&h=400&fit=crop',
      },
    ],
    customers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20456789012',
        name: 'TECNOLOGÍA DEL PERÚ SAC',
        email: 'ventas@tecnologia.com',
        phone: '987654321',
        address: 'Av. Arequipa 2580, Lima',
      },
      {
        id: '2',
        documentType: '1',
        documentNumber: '45678901',
        name: 'Juan Pérez García',
        email: 'juan.perez@email.com',
        phone: '987654322',
        address: 'Jr. Cusco 456, San Isidro',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20567890123',
        name: 'COMERCIAL LIMA SRL',
        email: 'compras@comerciallima.com',
        phone: '987654323',
        address: 'Av. Venezuela 1234, Lima',
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '32165498',
        name: 'María Fernández López',
        email: 'maria.fernandez@email.com',
        phone: '987654324',
        address: 'Av. Larco 890, Miraflores',
      },
    ],
    invoices: [
      {
        id: '1',
        number: 'F001-00000001',
        series: 'F001',
        documentType: 'factura',
        customer: {
          documentType: '6',
          documentNumber: '20456789012',
          name: 'TECNOLOGÍA DEL PERÚ SAC',
          phone: '987654321',
          email: 'ventas@tecnologia.com',
          address: 'Av. Arequipa 2580, Lima',
        },
        items: [
          {
            code: 'PROD001',
            description: 'Laptop HP 15"',
            quantity: 2,
            price: 2500.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 2,
            price: 45.00,
          },
        ],
        subtotal: 5090.00,
        tax: 916.20,
        total: 6006.20,
        status: 'paid',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 15),
      },
      {
        id: '2',
        number: 'B001-00000001',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '45678901',
          name: 'Juan Pérez García',
          phone: '987654322',
          email: 'juan.perez@email.com',
          address: 'Jr. Cusco 456, San Isidro',
        },
        items: [
          {
            code: 'PROD003',
            description: 'Teclado Mecánico',
            quantity: 1,
            price: 180.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 1,
            price: 45.00,
          },
        ],
        subtotal: 225.00,
        tax: 40.50,
        total: 265.50,
        status: 'paid',
        paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 18),
      },
      {
        id: '3',
        number: 'F001-00000002',
        series: 'F001',
        documentType: 'factura',
        customer: {
          documentType: '6',
          documentNumber: '20567890123',
          name: 'COMERCIAL LIMA SRL',
          phone: '987654323',
          email: 'compras@comerciallima.com',
          address: 'Av. Venezuela 1234, Lima',
        },
        items: [
          {
            code: 'PROD004',
            description: 'Monitor 24"',
            quantity: 5,
            price: 650.00,
          },
          {
            code: 'SERV001',
            description: 'Servicio de Instalación',
            quantity: 5,
            price: 120.00,
          },
        ],
        subtotal: 3850.00,
        tax: 693.00,
        total: 4543.00,
        status: 'pending',
        paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 20),
      },
      {
        id: '4',
        number: 'B001-00000002',
        series: 'B001',
        documentType: 'boleta',
        customer: {
          documentType: '1',
          documentNumber: '32165498',
          name: 'María Fernández López',
          phone: '987654324',
          email: 'maria.fernandez@email.com',
        },
        items: [
          {
            code: 'SERV002',
            description: 'Limpieza Facial Profunda',
            quantity: 1,
            price: 120.00,
          },
          {
            code: 'PROD005',
            description: 'Crema Hidratante Facial',
            quantity: 1,
            price: 85.00,
          },
        ],
        subtotal: 205.00,
        tax: 36.90,
        total: 241.90,
        status: 'paid',
        paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 22),
      },
      // Más ventas del mes actual
      {
        id: '5',
        number: 'B001-00000003',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '71234567', name: 'Carlos Mendoza' },
        items: [
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 2, price: 250.00 },
        ],
        subtotal: 500.00, tax: 90.00, total: 590.00,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 1),
      },
      {
        id: '6',
        number: 'B001-00000004',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '72345678', name: 'Ana Torres' },
        items: [
          { code: 'PROD010', description: 'Mascarilla Facial', quantity: 5, price: 35.00 },
          { code: 'PROD011', description: 'Sérum Vitamina C', quantity: 2, price: 95.00 },
        ],
        subtotal: 365.00, tax: 65.70, total: 430.70,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 2),
      },
      {
        id: '7',
        number: 'F001-00000003',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20512345678', name: 'DISTRIBUIDORA NORTE SAC' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 3, price: 2500.00 },
          { code: 'PROD008', description: 'Webcam HD 1080p', quantity: 3, price: 180.00 },
        ],
        subtotal: 8040.00, tax: 1447.20, total: 9487.20,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 3),
      },
      {
        id: '8',
        number: 'B001-00000005',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '73456789', name: 'Roberto Sánchez' },
        items: [
          { code: 'PROD002', description: 'Mouse Inalámbrico', quantity: 1, price: 45.00 },
          { code: 'PROD003', description: 'Teclado Mecánico', quantity: 1, price: 180.00 },
        ],
        subtotal: 225.00, tax: 40.50, total: 265.50,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 4),
      },
      {
        id: '9',
        number: 'B001-00000006',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '74567890', name: 'Lucía Vargas' },
        items: [
          { code: 'SERV002', description: 'Limpieza Facial Profunda', quantity: 1, price: 120.00 },
          { code: 'PROD005', description: 'Crema Hidratante Facial', quantity: 2, price: 85.00 },
        ],
        subtotal: 290.00, tax: 52.20, total: 342.20,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '10',
        number: 'F001-00000004',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20567890123', name: 'COMERCIAL LIMA SRL' },
        items: [
          { code: 'PROD009', description: 'Hub USB 7 puertos', quantity: 20, price: 85.00 },
        ],
        subtotal: 1700.00, tax: 306.00, total: 2006.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 6),
      },
      {
        id: '11',
        number: 'B001-00000007',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '75678901', name: 'Pedro Ramírez' },
        items: [
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 1, price: 250.00 },
        ],
        subtotal: 250.00, tax: 45.00, total: 295.00,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 7),
      },
      {
        id: '12',
        number: 'B001-00000008',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '76789012', name: 'Carmen Flores' },
        items: [
          { code: 'SERV003', description: 'Masaje Relajante con Aromaterapia', quantity: 1, price: 180.00 },
          { code: 'PROD006', description: 'Aceite Esencial Lavanda', quantity: 1, price: 65.00 },
        ],
        subtotal: 245.00, tax: 44.10, total: 289.10,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 8),
      },
      {
        id: '13',
        number: 'F001-00000005',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20456789012', name: 'TECNOLOGÍA DEL PERÚ SAC' },
        items: [
          { code: 'PROD004', description: 'Monitor 24"', quantity: 10, price: 650.00 },
          { code: 'PROD002', description: 'Mouse Inalámbrico', quantity: 10, price: 45.00 },
        ],
        subtotal: 6950.00, tax: 1251.00, total: 8201.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 9),
      },
      {
        id: '14',
        number: 'B001-00000009',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '77890123', name: 'Miguel Castillo' },
        items: [
          { code: 'PROD012', description: 'Kit Manicure Profesional', quantity: 1, price: 120.00 },
        ],
        subtotal: 120.00, tax: 21.60, total: 141.60,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 10),
      },
      {
        id: '15',
        number: 'B001-00000010',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '78901234', name: 'Rosa Medina' },
        items: [
          { code: 'PROD008', description: 'Webcam HD 1080p', quantity: 1, price: 180.00 },
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 1, price: 250.00 },
        ],
        subtotal: 430.00, tax: 77.40, total: 507.40,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 11),
      },
      {
        id: '16',
        number: 'F001-00000006',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20623456789', name: 'IMPORTACIONES SUR EIRL' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 5, price: 2500.00 },
          { code: 'SERV001', description: 'Servicio de Instalación', quantity: 5, price: 120.00 },
        ],
        subtotal: 13100.00, tax: 2358.00, total: 15458.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 12),
      },
      {
        id: '17',
        number: 'B001-00000011',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '79012345', name: 'Diana Rojas' },
        items: [
          { code: 'PROD010', description: 'Mascarilla Facial', quantity: 3, price: 35.00 },
          { code: 'PROD005', description: 'Crema Hidratante Facial', quantity: 1, price: 85.00 },
        ],
        subtotal: 190.00, tax: 34.20, total: 224.20,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 13),
      },
      {
        id: '18',
        number: 'B001-00000012',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '80123456', name: 'Jorge Gutiérrez' },
        items: [
          { code: 'PROD003', description: 'Teclado Mecánico', quantity: 2, price: 180.00 },
          { code: 'PROD002', description: 'Mouse Inalámbrico', quantity: 2, price: 45.00 },
        ],
        subtotal: 450.00, tax: 81.00, total: 531.00,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 14),
      },
      {
        id: '19',
        number: 'F001-00000007',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20734567890', name: 'SERVICIOS INTEGRALES SAC' },
        items: [
          { code: 'PROD004', description: 'Monitor 24"', quantity: 8, price: 650.00 },
          { code: 'PROD008', description: 'Webcam HD 1080p', quantity: 8, price: 180.00 },
          { code: 'PROD009', description: 'Hub USB 7 puertos', quantity: 8, price: 85.00 },
        ],
        subtotal: 7320.00, tax: 1317.60, total: 8637.60,
        status: 'pending', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 16),
      },
      {
        id: '20',
        number: 'B001-00000013',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '81234567', name: 'Sofía Herrera' },
        items: [
          { code: 'SERV002', description: 'Limpieza Facial Profunda', quantity: 1, price: 120.00 },
          { code: 'SERV003', description: 'Masaje Relajante con Aromaterapia', quantity: 1, price: 180.00 },
        ],
        subtotal: 300.00, tax: 54.00, total: 354.00,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 17),
      },
      {
        id: '21',
        number: 'B001-00000014',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '82345678', name: 'Fernando Díaz' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 1, price: 2500.00 },
        ],
        subtotal: 2500.00, tax: 450.00, total: 2950.00,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 19),
      },
      {
        id: '22',
        number: 'B001-00000015',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '83456789', name: 'Valentina Cruz' },
        items: [
          { code: 'PROD011', description: 'Sérum Vitamina C', quantity: 1, price: 95.00 },
          { code: 'PROD006', description: 'Aceite Esencial Lavanda', quantity: 2, price: 65.00 },
        ],
        subtotal: 225.00, tax: 40.50, total: 265.50,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 21),
      },
      {
        id: '23',
        number: 'F001-00000008',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20845678901', name: 'CORPORACIÓN ANDINA SAC' },
        items: [
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 15, price: 250.00 },
          { code: 'PROD002', description: 'Mouse Inalámbrico', quantity: 15, price: 45.00 },
        ],
        subtotal: 4425.00, tax: 796.50, total: 5221.50,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 23),
      },
      // Ventas del mes pasado
      {
        id: '24',
        number: 'B001-00000016',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '45678901', name: 'Juan Pérez García' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 1, price: 2500.00 },
        ],
        subtotal: 2500.00, tax: 450.00, total: 2950.00,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 2),
      },
      {
        id: '25',
        number: 'F001-00000009',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20456789012', name: 'TECNOLOGÍA DEL PERÚ SAC' },
        items: [
          { code: 'PROD003', description: 'Teclado Mecánico', quantity: 10, price: 180.00 },
          { code: 'PROD002', description: 'Mouse Inalámbrico', quantity: 10, price: 45.00 },
        ],
        subtotal: 2250.00, tax: 405.00, total: 2655.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 5),
      },
      {
        id: '26',
        number: 'B001-00000017',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '84567890', name: 'Gabriela Luna' },
        items: [
          { code: 'SERV002', description: 'Limpieza Facial Profunda', quantity: 1, price: 120.00 },
          { code: 'PROD010', description: 'Mascarilla Facial', quantity: 2, price: 35.00 },
        ],
        subtotal: 190.00, tax: 34.20, total: 224.20,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 8),
      },
      {
        id: '27',
        number: 'F001-00000010',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20567890123', name: 'COMERCIAL LIMA SRL' },
        items: [
          { code: 'PROD004', description: 'Monitor 24"', quantity: 6, price: 650.00 },
        ],
        subtotal: 3900.00, tax: 702.00, total: 4602.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
      },
      {
        id: '28',
        number: 'B001-00000018',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '85678901', name: 'Ricardo Vega' },
        items: [
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 1, price: 250.00 },
          { code: 'PROD008', description: 'Webcam HD 1080p', quantity: 1, price: 180.00 },
        ],
        subtotal: 430.00, tax: 77.40, total: 507.40,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 12),
      },
      {
        id: '29',
        number: 'F001-00000011',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20623456789', name: 'IMPORTACIONES SUR EIRL' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 4, price: 2500.00 },
          { code: 'PROD009', description: 'Hub USB 7 puertos', quantity: 4, price: 85.00 },
        ],
        subtotal: 10340.00, tax: 1861.20, total: 12201.20,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 15),
      },
      {
        id: '30',
        number: 'B001-00000019',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '86789012', name: 'Patricia Morales' },
        items: [
          { code: 'PROD005', description: 'Crema Hidratante Facial', quantity: 2, price: 85.00 },
          { code: 'PROD011', description: 'Sérum Vitamina C', quantity: 1, price: 95.00 },
        ],
        subtotal: 265.00, tax: 47.70, total: 312.70,
        status: 'paid', paymentMethod: 'Efectivo',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 18),
      },
      {
        id: '31',
        number: 'B001-00000020',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '87890123', name: 'Andrés Silva' },
        items: [
          { code: 'PROD003', description: 'Teclado Mecánico', quantity: 1, price: 180.00 },
        ],
        subtotal: 180.00, tax: 32.40, total: 212.40,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
      },
      {
        id: '32',
        number: 'F001-00000012',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20734567890', name: 'SERVICIOS INTEGRALES SAC' },
        items: [
          { code: 'PROD004', description: 'Monitor 24"', quantity: 12, price: 650.00 },
          { code: 'SERV001', description: 'Servicio de Instalación', quantity: 12, price: 120.00 },
        ],
        subtotal: 9240.00, tax: 1663.20, total: 10903.20,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 22),
      },
      {
        id: '33',
        number: 'B001-00000021',
        series: 'B001',
        documentType: 'boleta',
        customer: { documentType: '1', documentNumber: '88901234', name: 'Elena Ríos' },
        items: [
          { code: 'SERV003', description: 'Masaje Relajante con Aromaterapia', quantity: 1, price: 180.00 },
          { code: 'PROD012', description: 'Kit Manicure Profesional', quantity: 1, price: 120.00 },
        ],
        subtotal: 300.00, tax: 54.00, total: 354.00,
        status: 'paid', paymentMethod: 'Tarjeta',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 25),
      },
      {
        id: '34',
        number: 'F001-00000013',
        series: 'F001',
        documentType: 'factura',
        customer: { documentType: '6', documentNumber: '20845678901', name: 'CORPORACIÓN ANDINA SAC' },
        items: [
          { code: 'PROD001', description: 'Laptop HP 15"', quantity: 2, price: 2500.00 },
          { code: 'PROD007', description: 'Audífonos Bluetooth', quantity: 5, price: 250.00 },
        ],
        subtotal: 6250.00, tax: 1125.00, total: 7375.00,
        status: 'paid', paymentMethod: 'Transferencia',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 28),
      },
    ],
    quotations: [
      {
        id: '1',
        quotationNumber: 'COT001-00000001',
        series: 'COT001',
        customer: {
          documentType: '6',
          documentNumber: '20456789012',
          name: 'TECNOLOGÍA DEL PERÚ SAC',
          email: 'ventas@tecnologia.com',
          phone: '987654321',
          address: 'Av. Arequipa 2580, Lima',
        },
        items: [
          {
            code: 'PROD001',
            description: 'Laptop HP 15"',
            quantity: 3,
            price: 2500.00,
          },
          {
            code: 'PROD002',
            description: 'Mouse Inalámbrico',
            quantity: 3,
            price: 45.00,
          },
        ],
        subtotal: 7635.00,
        tax: 1374.30,
        total: 9009.30,
        status: 'pending',
        notes: 'Cotización válida por 15 días',
        validityDays: 15,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 15),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5),
        isSent: false,
        isConverted: false,
      },
      {
        id: '2',
        quotationNumber: 'COT001-00000002',
        series: 'COT001',
        customer: {
          documentType: '6',
          documentNumber: '20567890123',
          name: 'COMERCIAL LIMA SRL',
          email: 'compras@comerciallima.com',
          phone: '987654323',
          address: 'Av. Venezuela 1234, Lima',
        },
        items: [
          {
            code: 'PROD004',
            description: 'Monitor 24"',
            quantity: 10,
            price: 650.00,
          },
          {
            code: 'SERV001',
            description: 'Servicio de Instalación',
            quantity: 10,
            price: 120.00,
          },
        ],
        subtotal: 7700.00,
        tax: 1386.00,
        total: 9086.00,
        status: 'sent',
        notes: 'Incluye instalación y configuración',
        validityDays: 30,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 25),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2),
        isSent: true,
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isConverted: false,
      },
      {
        id: '3',
        quotationNumber: 'COT001-00000003',
        series: 'COT001',
        customer: {
          documentType: '1',
          documentNumber: '32165498',
          name: 'María Fernández López',
          email: 'maria.fernandez@email.com',
          phone: '987654324',
          address: 'Av. Larco 890, Miraflores',
        },
        items: [
          {
            code: 'SERV002',
            description: 'Limpieza Facial Profunda',
            quantity: 4,
            price: 120.00,
          },
          {
            code: 'SERV003',
            description: 'Masaje Relajante con Aromaterapia',
            quantity: 4,
            price: 180.00,
          },
        ],
        subtotal: 1200.00,
        tax: 216.00,
        total: 1416.00,
        status: 'approved',
        notes: 'Paquete mensual de tratamientos spa',
        validityDays: 7,
        expiryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 5),
        createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isSent: true,
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1),
        isConverted: false,
      },
    ],
    suppliers: [
      {
        id: '1',
        documentType: '6',
        documentNumber: '20123456789',
        businessName: 'DISTRIBUIDORA TECH SAC',
        contactName: 'Carlos Rodríguez',
        email: 'ventas@distribuidoratech.com',
        phone: '987123456',
        address: 'Av. Industrial 245, Ate',
      },
      {
        id: '2',
        documentType: '6',
        documentNumber: '20987654321',
        businessName: 'IMPORTACIONES GLOBAL SRL',
        contactName: 'María Fernández',
        email: 'compras@importacionesglobal.com',
        phone: '987123457',
        address: 'Jr. Comercio 890, Cercado de Lima',
      },
      {
        id: '3',
        documentType: '6',
        documentNumber: '20456789123',
        businessName: 'COSMÉTICOS NATURALES SAC',
        contactName: 'Laura Mendoza',
        email: 'ventas@cosmeticosnaturales.com',
        phone: '987123458',
        address: 'Av. Brasil 456, Jesús María',
      },
      {
        id: '4',
        documentType: '1',
        documentNumber: '43567890',
        businessName: 'SERVICIOS TÉCNICOS LÓPEZ',
        contactName: 'Luis López',
        email: 'luis.lopez@serviciotecnico.com',
        phone: '987123459',
        address: 'Av. Canadá 123, La Victoria',
      },
    ],
    purchases: [
      {
        id: '1',
        invoiceNumber: 'F001-00125',
        supplier: {
          id: '1',
          documentType: '6',
          documentNumber: '20123456789',
          businessName: 'DISTRIBUIDORA TECH SAC',
        },
        items: [
          {
            productId: '1',
            productName: 'Laptop HP 15"',
            quantity: 10,
            unitPrice: 1800.00,
          },
          {
            productId: '2',
            productName: 'Mouse Inalámbrico',
            quantity: 50,
            unitPrice: 25.00,
          },
        ],
        subtotal: 19250.00,
        igv: 3465.00,
        total: 22715.00,
        notes: 'Primera compra del mes',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
      {
        id: '2',
        invoiceNumber: 'F001-00234',
        supplier: {
          id: '2',
          documentType: '6',
          documentNumber: '20987654321',
          businessName: 'IMPORTACIONES GLOBAL SRL',
        },
        items: [
          {
            productId: '4',
            productName: 'Monitor 24"',
            quantity: 20,
            unitPrice: 450.00,
          },
        ],
        subtotal: 9000.00,
        igv: 1620.00,
        total: 10620.00,
        notes: 'Compra de monitores para stock',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 12),
      },
      {
        id: '3',
        invoiceNumber: 'F002-00089',
        supplier: {
          id: '3',
          documentType: '6',
          documentNumber: '20456789123',
          businessName: 'COSMÉTICOS NATURALES SAC',
        },
        items: [
          {
            productId: '5',
            productName: 'Crema Hidratante Facial',
            quantity: 24,
            unitPrice: 45.00,
          },
          {
            productId: '6',
            productName: 'Aceite Esencial Lavanda',
            quantity: 18,
            unitPrice: 28.00,
          },
        ],
        subtotal: 1584.00,
        igv: 285.12,
        total: 1869.12,
        notes: 'Productos de belleza para stock',
        createdAt: new Date(today.getFullYear(), today.getMonth(), 18),
      },
      // Compra del mes pasado
      {
        id: '4',
        invoiceNumber: 'F001-00098',
        supplier: {
          id: '1',
          documentType: '6',
          documentNumber: '20123456789',
          businessName: 'DISTRIBUIDORA TECH SAC',
        },
        items: [
          {
            productId: '3',
            productName: 'Teclado Mecánico',
            quantity: 30,
            unitPrice: 120.00,
          },
        ],
        subtotal: 3600.00,
        igv: 648.00,
        total: 4248.00,
        notes: 'Reposición de stock',
        createdAt: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
      },
    ],
    subscription: {
      status: 'active',
      plan: 'unlimited_12_months',
      currentPeriodEnd: new Date(today.getFullYear() + 1, today.getMonth(), today.getDate()),
      accessBlocked: false,
    },
    warehouses: [
      {
        id: '1',
        name: 'Almacén Principal',
        location: 'Av. Larco 1234, Miraflores',
        isDefault: true,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 2, 1),
      },
      {
        id: '2',
        name: 'Almacén Secundario',
        location: 'Jr. Comercio 567, San Isidro',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth() - 1, 15),
      },
      {
        id: '3',
        name: 'Almacén de Belleza',
        location: 'Av. Larco 1234, Miraflores',
        isDefault: false,
        isActive: true,
        createdAt: new Date(today.getFullYear(), today.getMonth(), 5),
      },
    ],
    categories: [
      // Categorías principales
      { id: 'cat-electronica', name: 'Electrónica', parentId: null },
      { id: 'cat-belleza', name: 'Belleza', parentId: null },
      { id: 'cat-servicios-tecnicos', name: 'Servicios Técnicos', parentId: null },
      { id: 'cat-servicios-spa', name: 'Servicios Spa', parentId: null },
    ],
    expenses: [
      // Gastos del mes actual
      {
        id: 'exp1',
        date: new Date(today.getFullYear(), today.getMonth(), 5),
        description: 'Pago de luz del local',
        category: 'servicios',
        supplier: 'Luz del Sur',
        reference: 'REC-2024-001',
        paymentMethod: 'transferencia',
        amount: 450.00,
      },
      {
        id: 'exp2',
        date: new Date(today.getFullYear(), today.getMonth(), 8),
        description: 'Internet y teléfono',
        category: 'servicios',
        supplier: 'Movistar',
        reference: 'FAC-123456',
        paymentMethod: 'transferencia',
        amount: 180.00,
      },
      {
        id: 'exp3',
        date: new Date(today.getFullYear(), today.getMonth(), 10),
        description: 'Compra de mercadería electrónica',
        category: 'proveedores',
        supplier: 'Tech Import SAC',
        reference: 'FAC-001-0045',
        paymentMethod: 'transferencia',
        amount: 8500.00,
      },
      {
        id: 'exp4',
        date: new Date(today.getFullYear(), today.getMonth(), 12),
        description: 'Combustible delivery',
        category: 'transporte',
        supplier: 'Grifo Repsol',
        reference: '',
        paymentMethod: 'efectivo',
        amount: 250.00,
      },
      {
        id: 'exp5',
        date: new Date(today.getFullYear(), today.getMonth(), 15),
        description: 'Sueldos del mes',
        category: 'personal',
        supplier: '',
        reference: 'PLANILLA-DIC',
        paymentMethod: 'transferencia',
        amount: 4500.00,
      },
      {
        id: 'exp6',
        date: new Date(today.getFullYear(), today.getMonth(), 3),
        description: 'Publicidad en redes sociales',
        category: 'marketing',
        supplier: 'Meta Ads',
        reference: 'INV-META-001',
        paymentMethod: 'transferencia',
        amount: 350.00,
      },
      {
        id: 'exp7',
        date: new Date(today.getFullYear(), today.getMonth(), 7),
        description: 'Mantenimiento de computadoras',
        category: 'mantenimiento',
        supplier: 'Soporte TI',
        reference: 'SRV-2024-089',
        paymentMethod: 'efectivo',
        amount: 200.00,
      },
      // Gastos del mes anterior
      {
        id: 'exp8',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 5),
        description: 'Pago de luz del local',
        category: 'servicios',
        supplier: 'Luz del Sur',
        reference: 'REC-2024-000',
        paymentMethod: 'transferencia',
        amount: 420.00,
      },
      {
        id: 'exp9',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 10),
        description: 'Alquiler del local',
        category: 'servicios',
        supplier: 'Inmobiliaria Central',
        reference: 'ALQ-NOV-2024',
        paymentMethod: 'transferencia',
        amount: 2500.00,
      },
      {
        id: 'exp10',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 12),
        description: 'Compra de productos de belleza',
        category: 'proveedores',
        supplier: 'Cosméticos Perú',
        reference: 'FAC-002-0089',
        paymentMethod: 'transferencia',
        amount: 3200.00,
      },
      {
        id: 'exp11',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 15),
        description: 'Sueldos del mes',
        category: 'personal',
        supplier: '',
        reference: 'PLANILLA-NOV',
        paymentMethod: 'transferencia',
        amount: 4500.00,
      },
      {
        id: 'exp12',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 20),
        description: 'Pago IGV mensual',
        category: 'impuestos',
        supplier: 'SUNAT',
        reference: 'DEC-IGV-NOV',
        paymentMethod: 'transferencia',
        amount: 1850.00,
      },
      {
        id: 'exp13',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 22),
        description: 'Comisiones bancarias',
        category: 'bancarios',
        supplier: 'BCP',
        reference: '',
        paymentMethod: 'transferencia',
        amount: 85.00,
      },
      {
        id: 'exp14',
        date: new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 25),
        description: 'Delivery y envíos',
        category: 'transporte',
        supplier: 'Olva Courier',
        reference: 'SRV-NOV-2024',
        paymentMethod: 'efectivo',
        amount: 380.00,
      },
    ],
  }
}

export const DemoProvider = ({ children }) => {
  const [demoData] = useState(generateDemoData())

  // Inyectar datos de demo en window para que los servicios puedan acceder
  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.__DEMO_DATA__ = demoData
    }
    return () => {
      if (typeof window !== 'undefined') {
        delete window.__DEMO_DATA__
      }
    }
  }, [demoData])

  const value = {
    isDemoMode: true,
    demoData,
  }

  return <DemoContext.Provider value={value}>{children}</DemoContext.Provider>
}

export const useDemo = () => {
  const context = useContext(DemoContext)
  // No lanzar error si no está en un provider, simplemente retornar null
  // Esto permite usar el hook condicionalmente
  return context
}
