export { default as Pagina } from './Pagina'
export { default as Seccion } from './Seccion'
export { Tabla, Th, Td, Fila, FilaVacia } from './Tabla'
export { Filtros, FiltroSelect, Buscador } from './Filtros'
export { default as Estado } from './Estado'
export { default as Pastilla } from './Pastilla'
export { default as Boton } from './Boton'
export { ListaDatos, Dato } from './ListaDatos'
export { Cifras, Cifra } from './Cifras'
export { default as Aviso } from './Aviso'
export { default as Modal } from './Modal'
export { Campo, Entrada, Selector, AreaTexto, Casilla, Opcion } from './Campo'
export { useTituloAdmin } from './tituloAdmin'
