/**
 * PÁGINAS LEGALES de CITEX, copiadas de su web (citex.com.pe, 15-set-2026) para
 * que vivan en citex.pe: Luis pidió que ningún enlace salga del dominio. Si él
 * cambia sus políticas, esto se cambia a mano: no se sincroniza solo.
 *
 * Cada página: título, nombre corto (migas y pie), subtítulo, fecha,
 * descripción (para el SEO) y bloques en orden: { t: 'p' | 'h2' | 'ul', x }
 * (x = texto, o lista de textos en 'ul'). JavaScript puro: también lo leen
 * las funciones de Vercel (api/domain-meta) a través de ./seo.js.
 */
export const LEGALES = {
  'politica-privacidad': {
    titulo: 'Política de privacidad',
    corto: 'Privacidad',
    subtitulo: 'Protección de datos personales según Ley N.° 29733',
    actualizado: '06/09/2026',
    descripcion: 'Consulta la política de privacidad de CITEX y el tratamiento de datos personales conforme a la Ley N.° 29733 del Perú.',
    bloques: [
      { t: 'p', x: 'En CITEX protegemos la información personal de nuestros clientes, usuarios y proveedores, en cumplimiento de la Ley N.° 29733 – Ley de Protección de Datos Personales, su reglamento y las disposiciones aplicables de Indecopi.' },
      { t: 'h2', x: '1. Identidad del responsable' },
      { t: 'p', x: 'CITEX es el responsable del tratamiento de los datos personales recopilados a través de su sitio web (Plataforma Firebase), formularios digitales, WhatsApp, redes sociales y tienda física.' },
      { t: 'h2', x: '2. Datos personales recopilados' },
      { t: 'p', x: 'CITEX puede recopilar, según el canal de atención, los siguientes datos personales:' },
      { t: 'ul', x: [
        'Nombre y apellidos',
        'Número de documento de identidad (cuando sea requerido para facturación)',
        'Número de teléfono',
        'Correo electrónico',
        'Dirección de envío',
        'Información necesaria para la emisión de comprobantes de pago',
      ] },
      { t: 'h2', x: '3. Finalidad del tratamiento' },
      { t: 'ul', x: [
        'Atender consultas y solicitudes de información',
        'Procesar pedidos, ventas y despachos',
        'Emitir boletas y facturas',
        'Brindar atención postventa',
        'Enviar comunicaciones comerciales, promociones u ofertas, previo consentimiento del titular',
      ] },
      { t: 'h2', x: '4. Carácter obligatorio o facultativo de los datos' },
      { t: 'p', x: 'Los datos solicitados para la atención de pedidos y facturación son obligatorios. La negativa a proporcionarlos puede impedir la correcta prestación del servicio. El envío de información comercial es facultativo y requiere autorización expresa.' },
      { t: 'h2', x: '5. Uso de cookies y tecnologías web' },
      { t: 'p', x: 'CITEX utiliza cookies esenciales para recordar las preferencias del sitio. Las cookies de analítica de Meta Pixel y TikTok Pixel solo se activan cuando el usuario las acepta mediante el aviso de cookies. El usuario puede aceptar o rechazar las cookies no esenciales y cambiar su decisión desde el botón “Cookies”.' },
      { t: 'h2', x: '6. Seguridad y confidencialidad' },
      { t: 'p', x: 'CITEX adopta las medidas técnicas y organizativas necesarias para garantizar la seguridad de los datos personales y evitar su alteración, pérdida, tratamiento o acceso no autorizado.' },
      { t: 'h2', x: '7. Transferencia y tratamiento por terceros' },
      { t: 'p', x: 'Los datos personales no serán vendidos ni cedidos a terceros, salvo cuando sea necesario para:' },
      { t: 'ul', x: [
        'Cumplir obligaciones legales',
        'Ejecutar correctamente el servicio contratado (por ejemplo, empresas de transporte o plataformas de pago)',
      ] },
      { t: 'p', x: 'En estos casos, los datos se comparten únicamente para la finalidad correspondiente.' },
      { t: 'h2', x: '8. Plazo de conservación' },
      { t: 'p', x: 'Los datos personales serán conservados por el tiempo necesario para cumplir las finalidades para las cuales fueron recopilados o mientras exista una relación comercial, y conforme a los plazos legales vigentes.' },
      { t: 'h2', x: '9. Derechos del titular de los datos (ARCO)' },
      { t: 'p', x: 'El titular de los datos personales puede ejercer sus derechos de:' },
      { t: 'ul', x: [
        'Acceso',
        'Rectificación',
        'Cancelación',
        'Oposición',
      ] },
      { t: 'p', x: 'mediante solicitud a través de los canales de atención de CITEX, conforme a la Ley N.° 29733.' },
      { t: 'h2', x: '10. Consentimiento' },
      { t: 'p', x: 'El consentimiento para cookies no esenciales es libre, informado y puede retirarse en cualquier momento desde el botón “Cookies”, sin afectar el acceso al sitio. La aceptación de esta Política de Privacidad no se presume por la simple navegación.' },
      { t: 'h2', x: '11. Modificaciones' },
      { t: 'p', x: 'CITEX se reserva el derecho de modificar esta Política de Privacidad en cualquier momento. Las modificaciones serán publicadas en el sitio web y entrarán en vigencia desde su publicación.' },
      { t: 'p', x: 'Fabricamos polos esenciales para marcas que quieren crecer. Con acabados de primera. Desde Gamarra para todo el Perú.' },
      { t: 'p', x: 'RUC: 20612459950' },
      { t: 'p', x: 'GRUPO CREATIVO INDEPENDIENTE TEXTIL E.I.R.L.' },
      { t: 'p', x: 'Nombre comercial: CITEX' },
      { t: 'p', x: 'Fiscal: Av. Mexico 1590, LA VICTORIA' },
      { t: 'p', x: 'Tienda: JR. MARISCAL AGUSTÍN GAMARRA NRO 1215-1275 (TIENDA TN 272 PISO 3 CENTRO COMERCIAL GAMA) LIMA - LIMA - LA VICTORIA' },
    ],
  },
  'politica-cambios-devoluciones': {
    titulo: 'Política de cambios y devoluciones',
    corto: 'Cambios y devoluciones',
    subtitulo: 'Condiciones para cambios, devoluciones y defectos de fabricación',
    actualizado: '06/09/2026',
    descripcion: 'Conoce la política de cambios, devoluciones y defectos de fabricación de CITEX para compras por web, WhatsApp y tienda física.',
    bloques: [
      { t: 'p', x: 'En CITEX realizamos ventas a través de sitio web, WhatsApp y tienda física. La presente política aplica para todas las modalidades de compra.' },
      { t: 'h2', x: '1. Condiciones generales' },
      { t: 'ul', x: [
        'Los cambios se aceptan únicamente dentro de las 48 horas posteriores a la compra o recepción del producto.',
        'Es obligatorio presentar el comprobante de pago (boleta o factura).',
        'El producto debe encontrarse sin uso, sin lavar, sin estampar, sin sublimar, y en las mismas condiciones en que fue entregado.',
      ] },
      { t: 'h2', x: '2. Compras por sitio web y WhatsApp' },
      { t: 'ul', x: [
        'Antes de confirmar la compra, el cliente recibe información detallada sobre tallas, modelos, cantidades y precios.',
        'Al confirmar el pago, el cliente acepta las características del producto solicitado.',
        'No se aceptan cambios por error en talla, modelo o cantidad una vez despachada la mercadería.',
      ] },
      { t: 'h2', x: '3. Compras en tienda física' },
      { t: 'ul', x: [
        'El cliente puede revisar el producto antes de pagar.',
        'No se aceptan cambios por error de elección luego de retirada la mercadería.',
      ] },
      { t: 'h2', x: '4. Productos sin cambio ni devolución' },
      { t: 'p', x: 'No se aceptan cambios ni devoluciones en los siguientes casos:' },
      { t: 'ul', x: [
        'Polos sublimados, estampados o personalizados.',
        'Productos usados, lavados, cortados o manipulados.',
        'Ventas al por mayor, salvo defecto de fabricación comprobado.',
        'Variaciones leves de tono, textura o encogimiento propias del proceso textil.',
      ] },
      { t: 'h2', x: '5. Defectos de fabricación' },
      { t: 'ul', x: [
        'El defecto debe ser comunicado dentro del plazo establecido.',
        'El producto será evaluado por CITEX.',
        'De confirmarse el defecto, se realizará únicamente el cambio del producto, sujeto a stock disponible.',
        'No se realizan devoluciones de dinero.',
      ] },
      { t: 'h2', x: '6. Aceptación de la política' },
      { t: 'p', x: 'Toda compra realizada en CITEX, a través del sitio web, WhatsApp o tienda física, implica la aceptación total de esta política de cambios y devoluciones.' },
      { t: 'p', x: 'Fabricamos polos esenciales para marcas que quieren crecer. Con acabados de primera. Desde Gamarra para todo el Perú.' },
      { t: 'p', x: 'RUC: 20612459950' },
      { t: 'p', x: 'GRUPO CREATIVO INDEPENDIENTE TEXTIL E.I.R.L.' },
      { t: 'p', x: 'Nombre comercial: CITEX' },
      { t: 'p', x: 'Fiscal: Av. Mexico 1590, LA VICTORIA' },
      { t: 'p', x: 'Tienda: JR. MARISCAL AGUSTÍN GAMARRA NRO 1215-1275 (TIENDA TN 272 PISO 3 CENTRO COMERCIAL GAMA) LIMA - LIMA - LA VICTORIA' },
    ],
  },
  'politica-envios': {
    titulo: 'Política de envíos',
    corto: 'Envíos',
    subtitulo: 'Envíos locales y nacionales vía courier externo',
    actualizado: '06/09/2026',
    descripcion: 'Conoce la política de envíos locales, nacionales y recojo en tienda de CITEX desde Gamarra, La Victoria.',
    bloques: [
      { t: 'p', x: 'En CITEX realizamos envíos a nivel local y nacional a través de empresas de transporte y courier externos. La presente política aplica para compras realizadas por sitio web, WhatsApp y tienda física.' },
      { t: 'h2', x: '1. Empresas de transporte' },
      { t: 'p', x: 'Los envíos se realizan mediante empresas de transporte o courier externos, elegidos por el cliente o sugeridos por CITEX. CITEX no fija ni controla las tarifas de envío.' },
      { t: 'h2', x: '2. Costo del envío' },
      { t: 'ul', x: [
        'El costo del envío es determinado exclusivamente por la empresa de transporte o courier externo, según peso, volumen y destino.',
        'Dicho costo es asumido íntegramente por el cliente.',
        'CITEX informará al cliente el método de envío y, cuando sea posible, un costo referencial, sin carácter vinculante.',
      ] },
      { t: 'h2', x: '3. Confirmación y despacho' },
      { t: 'ul', x: [
        'Los pedidos se despachan una vez confirmado el pago del producto.',
        'El despacho se realiza dentro de un plazo aproximado de 24 a 48 horas hábiles.',
        'Los tiempos de entrega dependen de la empresa de transporte y del destino.',
      ] },
      { t: 'h2', x: '4. Responsabilidad del envío' },
      { t: 'ul', x: [
        'CITEX es responsable del pedido hasta su entrega a la empresa de transporte.',
        'Una vez entregado el paquete, la responsabilidad por costos, tiempos de entrega, demoras, daños o pérdidas corresponde a la empresa de transporte o courier.',
        'El cliente recibirá el número de guía para seguimiento.',
      ] },
      { t: 'h2', x: '5. Datos de envío' },
      { t: 'ul', x: [
        'El cliente es responsable de proporcionar datos correctos y completos.',
        'Errores en la dirección o datos pueden generar costos adicionales, los cuales serán asumidos por el cliente.',
      ] },
      { t: 'h2', x: '6. Recepción del pedido' },
      { t: 'ul', x: [
        'El cliente debe revisar el estado del paquete al momento de recibirlo.',
        'Si el paquete presenta daños visibles, deberá registrar la observación directamente con la empresa de transporte antes de aceptar la entrega.',
      ] },
      { t: 'h2', x: '7. Pedidos no entregados o no reclamados' },
      { t: 'p', x: 'Los pedidos no reclamados, rechazados o con datos incorrectos podrán generar costos adicionales de retorno o reenvío, los cuales serán asumidos por el cliente.' },
      { t: 'h2', x: '8. Recojo en tienda' },
      { t: 'p', x: 'El cliente puede optar por recojo en tienda, previa coordinación. En este caso, no se generan costos de envío.' },
      { t: 'h2', x: '9. Aceptación de la política' },
      { t: 'p', x: 'Toda compra realizada en CITEX, por sitio web, WhatsApp o tienda física, implica la aceptación de la presente Política de Envíos.' },
      { t: 'h2', x: '10. Modificaciones' },
      { t: 'p', x: 'CITEX se reserva el derecho de modificar esta política en cualquier momento. Las modificaciones serán publicadas en el sitio web.' },
      { t: 'p', x: 'Fabricamos polos esenciales para marcas que quieren crecer. Con acabados de primera. Desde Gamarra para todo el Perú.' },
      { t: 'p', x: 'RUC: 20612459950' },
      { t: 'p', x: 'GRUPO CREATIVO INDEPENDIENTE TEXTIL E.I.R.L.' },
      { t: 'p', x: 'Nombre comercial: CITEX' },
      { t: 'p', x: 'Fiscal: Av. Mexico 1590, LA VICTORIA' },
      { t: 'p', x: 'Tienda: JR. MARISCAL AGUSTÍN GAMARRA NRO 1215-1275 (TIENDA TN 272 PISO 3 CENTRO COMERCIAL GAMA) LIMA - LIMA - LA VICTORIA' },
    ],
  },
  'terminos-condiciones': {
    titulo: 'Términos y condiciones de uso',
    corto: 'Términos y condiciones',
    subtitulo: 'Condiciones de uso para compras, cotizaciones y navegación',
    actualizado: '06/09/2026',
    descripcion: 'Lee los términos y condiciones de uso de CITEX para compras de polos por mayor y menor en el Perú.',
    bloques: [
      { t: 'p', x: 'Bienvenido(a) a CITEX. Al navegar por este sitio, solicitar cotizaciones o realizar compras por nuestros canales oficiales, aceptas cumplir los presentes Términos y Condiciones. Si no estás de acuerdo con alguno de ellos, te recomendamos no utilizar nuestros servicios.' },
      { t: 'h2', x: '1. IDENTIFICACIÓN DEL TITULAR' },
      { t: 'p', x: 'El presente sitio web es operado por CITEX, empresa dedicada a la fabricación y comercialización de polos de algodón, sublimación y prendas textiles, tanto al por mayor como al por menor, en el Perú.' },
      { t: 'h2', x: '2. INFORMACIÓN DEL CLIENTE' },
      { t: 'ul', x: [
        'El cliente se compromete a proporcionar información veraz, actualizada y completa al solicitar una cotización, compra o despacho.',
        'El cliente es responsable de revisar modelos, tallas, colores, cantidades y datos de envío antes de confirmar un pedido.',
        'CITEX se reserva el derecho de no atender solicitudes con información falsa, incompleta o uso indebido de sus canales.',
      ] },
      { t: 'h2', x: '3. USO DEL SITIO WEB' },
      { t: 'p', x: 'El usuario se compromete a:' },
      { t: 'ul', x: [
        'Usar el sitio únicamente para fines lícitos.',
        'No realizar actividades que puedan dañar, sobrecargar o afectar el funcionamiento del sitio.',
        'No intentar acceder sin autorización a sistemas, cuentas o bases de datos de CITEX.',
      ] },
      { t: 'h2', x: '4. PRODUCTOS Y COMPRAS' },
      { t: 'ul', x: [
        'CITEX comercializa polos de algodón, polos para sublimación y prendas textiles según disponibilidad.',
        'Las imágenes de los productos son referenciales.',
        'Los precios, promociones y disponibilidad pueden variar sin previo aviso.',
        'Las compras pueden realizarse por la web, WhatsApp o tienda física.',
      ] },
      { t: 'h2', x: '5. VENTAS MAYORISTAS' },
      { t: 'ul', x: [
        'Las condiciones de venta mayorista (precios, cantidades mínimas, plazos) pueden diferir de las ventas al por menor.',
        'CITEX se reserva el derecho de validar pedidos mayoristas antes de su confirmación.',
      ] },
      { t: 'h2', x: '6. FORMAS DE PAGO' },
      { t: 'p', x: 'Los métodos de pago disponibles serán informados en el sitio web o canales oficiales de CITEX. Todos los pagos están sujetos a validación.' },
      { t: 'h2', x: '7. ENVÍOS' },
      { t: 'p', x: 'Los envíos se realizan según las condiciones indicadas en la Política de Envíos del sitio. Los plazos de entrega son referenciales y pueden variar por causas externas.' },
      { t: 'h2', x: '8. CAMBIOS Y DEVOLUCIONES' },
      { t: 'p', x: 'Las condiciones para cambios y devoluciones se rigen por lo establecido en la Política de Cambios y Devoluciones publicada en el sitio web.' },
      { t: 'h2', x: '9. PROPIEDAD INTELECTUAL' },
      { t: 'p', x: 'Todo el contenido del sitio (textos, imágenes, logotipos, diseño) es propiedad de CITEX o cuenta con autorización para su uso. Queda prohibida su reproducción total o parcial sin autorización expresa.' },
      { t: 'h2', x: '10. PROTECCIÓN DE DATOS PERSONALES' },
      { t: 'p', x: 'Los datos personales proporcionados por el usuario serán tratados conforme a la Política de Privacidad de CITEX y a la legislación peruana vigente. El usuario autoriza el uso de sus datos para fines comerciales, informativos y operativos del servicio.' },
      { t: 'h2', x: '11. LIMITACIÓN DE RESPONSABILIDAD' },
      { t: 'p', x: 'CITEX no se responsabiliza por:' },
      { t: 'ul', x: [
        'Interrupciones temporales del sitio web.',
        'Daños derivados del uso indebido del sitio.',
        'Información incorrecta proporcionada por el usuario.',
      ] },
      { t: 'h2', x: '12. MODIFICACIONES' },
      { t: 'p', x: 'CITEX se reserva el derecho de modificar estos Términos y Condiciones en cualquier momento. Las modificaciones entrarán en vigor desde su publicación en el sitio web.' },
      { t: 'h2', x: '13. LEGISLACIÓN APLICABLE' },
      { t: 'p', x: 'Estos Términos y Condiciones se rigen por las leyes de la República del Perú. Cualquier controversia será resuelta por los tribunales competentes del país.' },
      { t: 'p', x: 'Fabricamos polos esenciales para marcas que quieren crecer. Con acabados de primera. Desde Gamarra para todo el Perú.' },
      { t: 'p', x: 'RUC: 20612459950' },
      { t: 'p', x: 'GRUPO CREATIVO INDEPENDIENTE TEXTIL E.I.R.L.' },
      { t: 'p', x: 'Nombre comercial: CITEX' },
      { t: 'p', x: 'Fiscal: Av. Mexico 1590, LA VICTORIA' },
      { t: 'p', x: 'Tienda: JR. MARISCAL AGUSTÍN GAMARRA NRO 1215-1275 (TIENDA TN 272 PISO 3 CENTRO COMERCIAL GAMA) LIMA - LIMA - LA VICTORIA' },
    ],
  },
}

/** El orden en que se listan en el pie y al final de cada página. */
export const ORDEN_LEGALES = ['politica-privacidad', 'politica-cambios-devoluciones', 'politica-envios', 'terminos-condiciones']
